### ISSUE TITLE
[Bug] null pointer crasher when running market sim

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#10168]
A new one:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1057a8124]

goroutine 38279 [running]:
code.vegaprotocol.io/vega/core/collateral.(*Engine).getTransferRequest(0x1400031a700, 0x0, 0x14006f65400, 0x14006f65310, 0x1400afd6f00)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/collateral/engine.go:2660 +0x34
code.vegaprotocol.io/vega/core/collateral.(*Engine).mtmOrFundingSettlement(0x1400031a700, {0x10839adb8, 0x140029df380}, {0x14001ed0c40, 0x40}, {0x140044c1600, 0x6, 0x2c}, {0x14001ed0840, 0x40}, ...)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/collateral/engine.go:1526 +0x2688
code.vegaprotocol.io/vega/core/collateral.(*Engine).MarkToMarket(0x14004756ce0?, {0x10839adb8?, 0x140029df380?}, {0x14001ed0c40?, 0x6?}, {0x140044c1600?, 0x1400472d700?, 0x20?}, {0x14001ed0840?, 0x14004731b00?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/collateral/engine.go:1315 +0x38
code.vegaprotocol.io/vega/core/execution/future.(*Market).collateralAndRisk(0x1400069eb00, {0x10839adb8, 0x140029df380}, {0x140044c1600, 0x6, 0x2c})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/future/market.go:2631 +0x15c
code.vegaprotocol.io/vega/core/execution/future.(*Market).confirmMTM(0x1400069eb00, {0x10839adb8, 0x140029df380}, 0x0)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/future/market.go:2302 +0x2c8
code.vegaprotocol.io/vega/core/execution/future.(*Market).checkNetwork(0x1400069eb00, {0x10839adb8, 0x140029df380}, {0x1400d46e640?, 0x14004746b38?, 0x0?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/future/liquidation.go:90 +0x38c
code.vegaprotocol.io/vega/core/execution/future.(*Market).OnTick(0x1400069eb00, {0x10839adb8, 0x140029df380}, {0x40?, 0x0?, 0x0?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/future/market.go:894 +0x2a0
code.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0x14000354580, {0x10839adb8, 0x140029df380}, {0x1?, 0x1083b54f0?, 0x0?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/execution/engine.go:1307 +0x398
code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/vegatime/service.go:107
code.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0x140002a0500, {0x10839adb8, 0x140029df380}, {0x40?, 0x10a4e5518?, 0x0?})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/vegatime/service.go:80 +0x26c
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(0x14000c7d880, 0xc94, {0x1400d46e440, 0x40}, {0x1400d46e440?, 0x0?, 0x0?}, {0x0, 0x0}, {0x10a4e5518?, ...})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/processor/abci.go:963 +0x794
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0x1400020a000, {0x108185c80?, 0x1?}, 0x14003495ec0)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/abci/abci.go:162 +0x330
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0x1400c3fd680?, {0x10839ad48?, 0x14000190010?}, 0x14001d66e58?)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x30
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0x140002c8120)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/nullchain/nullchain.go:198 +0x448
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0x140002c8120, 0x77359400)
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/nullchain/nullchain.go:275 +0x198
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/nullchain/server.go:132 +0x2c
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/blockchain/nullchain/server.go:131 +0x1ec
```
[replay.zip](https://github.com/vegaprotocol/vega/files/13451314/replay.zip)

**Comment by davidsiska-vega** [comment]
And this is the version (for replay):
```
git log
commit efed0e338e6806a9bf885299bd8c35fc54ccf7a8 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 07b6292ce 08f5824bf
Author: Elias Van Ootegem <EVODelavega@users.noreply.github.com>
Date:   Wed Nov 22 17:46:57 2023 +0000

    Merge pull request #10161 from vegaprotocol/10158-panic-fix
    
    fix: Add unit test with small fix
```
