### ISSUE TITLE
[Bug]: Spot failure in snapshot

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#10721]
### Problem encountered

this was reported in slack last week but since its not been fixed created a ticket to track the issue
https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1708008420074949

```

[2024-02-16T09:54:53.182Z] snapshot general failure restore block: 1645

[2024-02-16T09:54:53.182Z] panic: expecting a state variable with id to exist during post restore

[2024-02-16T09:54:53.182Z] 

[2024-02-16T09:54:53.182Z] goroutine 1 [running]:

[2024-02-16T09:54:53.182Z] go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc0005ec120?})

[2024-02-16T09:54:53.182Z] 	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54

[2024-02-16T09:54:53.182Z] go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc001029040, {0xc00139b880, 0x1, 0x1})

[2024-02-16T09:54:53.182Z] 	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec

[2024-02-16T09:54:53.182Z] go.uber.org/zap.(*Logger).Panic(0x2340?, {0x5aaf0d7?, 0xc0013a4630?}, {0xc00139b880, 0x1, 0x1})

[2024-02-16T09:54:53.182Z] 	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/core/statevar.(*Engine).postRestore(0xc000d7e4d0, {0xc0007d6400, 0x14, 0x61c41d0?})

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/core/statevar/snapshot.go:162 +0x28b

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/core/statevar.(*Engine).OnStateLoaded(0xc000d7e4d0, {0x61d2d28?, 0xc001228b40?})

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/core/statevar/snapshot.go:192 +0x1da

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/core/snapshot.(*Engine).restoreStateFromSnapshot(0xc00103e3c0, {0x61d2d60, 0xc000abda40}, {0xc000d86c00?, 0xcb?, 0x6693f18?})

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:866 +0x849

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/core/snapshot.(*Engine).restoreStateFromTree(0xc00103e3c0, {0x61d2d60, 0xc000abda40})

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:804 +0x135

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/core/snapshot.(*Engine).Start(0xc00103e3c0, {0x61d2d60, 0xc000abda40})

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:205 +0xb1

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/core/protocol.(*Protocol).Start(0xc000addb00?, {0x61d2d60?, 0xc000abda40?})

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/core/protocol/protocol.go:163 +0x28

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run(0xc000addb00, 0xc000767800, {0x61f8ef8?, 0xc000d2bb00}, {0x0, 0x0}, {0x7ffe727cf05e, 0x53}, {0x0, 0x0}, ...)

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:146 +0x59c

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/cmd/vega/commands.(*StartCmd).Execute(0x88b47e0, {0x5517940, 0x88b47e0, 0x1f})

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node.go:107 +0x80e

[2024-02-16T09:54:53.182Z] github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000ab3ec0, {0xc000160010?, 0x4, 0x4})

[2024-02-16T09:54:53.182Z] 	/jenkins/GOPATH/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x86f

[2024-02-16T09:54:53.182Z] github.com/jessevdk/go-flags.(*Parser).Parse(...)

[2024-02-16T09:54:53.182Z] 	/jenkins/GOPATH/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186

[2024-02-16T09:54:53.182Z] code.vegaprotocol.io/vega/cmd/vega/commands.Main({0x61d2cf0, 0x88ec360})

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/root.go:92 +0x538

[2024-02-16T09:54:53.182Z] main.main()

[2024-02-16T09:54:53.182Z] 	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/main.go:27 +0x25
```

### Observed behaviour

soak test failure

### Expected behaviour

no soak failure

### Steps to reproduce

```bash
1. run the test on ST branch `term-spot-via-governance`
```

### Software version

dev branch

### Failing test

test_terminate_spot_market

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/45066/

**Comment by Sohill-Patel** [comment]
recent pipeline with the bug
https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/49410/pipeline
