### ISSUE TITLE
[Bug]: new spot market proposal soak failure

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#10739]
### Problem encountered

This panic looks to happen after a future market test is complete
Running the spot test or the future test on its own b2b does not produce this issue, only by running them consecutively do we see this issue

```
Block: Block{
  Header{
    Version:        {11 1}
    ChainID:        testnet-001
    Height:         283
    Time:           2024-02-23 10:14:54.786544596 +0000 UTC
    LastBlockID:    ED9E9B476E324724F1C6CDEC509660ECB24FDBBDD044D6B2ADF14D3B6AD59AEF:1:0AA686C5AFC9
    LastCommit:     8DA0BA513467D0BDD25BCED752456416A10937ECC0A4CA6C802D1A07E383F529
    Data:           E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Validators:     6B2FB6533A26B4387B6AFE6ED0D94187B65401B2227DD2557F522223F5DFF0AB
    NextValidators: 6B2FB6533A26B4387B6AFE6ED0D94187B65401B2227DD2557F522223F5DFF0AB
    App:            E1D15777F4E310E8F15FFE2CF1FF76D70B1E181962D5FA1E1E954E086BCA1753
    Consensus:      6486D15E453CB23080B12B30E84A049298B8758042C8F0F10B5721988850E5C4
    Results:        E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Evidence:       E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Proposer:       02D365B2CF0F15D982BCB715D42014FECF83FC87
  }#67E4C0C71B68B5928E57EBE43B626B093ED95766B11E811CA1FC598AB7EB5BE4
  Data{
    
  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  EvidenceData{
    
  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  Commit{
    Height:     282
    Round:      0
    BlockID:    ED9E9B476E324724F1C6CDEC509660ECB24FDBBDD044D6B2ADF14D3B6AD59AEF:1:0AA686C5AFC9
    Signatures:
      CommitSig{99F7BB628FE9 by 02D365B2CF0F on 2 @ 2024-02-23T10:14:54.786544596Z}
      CommitSig{3B8B27FE810C by 30696050B226 on 2 @ 2024-02-23T10:14:54.887823126Z}
  }#8DA0BA513467D0BDD25BCED752456416A10937ECC0A4CA6C802D1A07E383F529
}#67E4C0C71B68B5928E57EBE43B626B093ED95766B11E811CA1FC598AB7EB5BE4


goroutine 191 [running]:
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1.1()
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:160 +0x54
panic({0x4f4cfa0?, 0xc000d39c50?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cometbft/cometbft/consensus.assertAppHashEqualsOneFromBlock({0xc000eeb780, 0x20, 0x20}, 0xc002b201e0)
	/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:546 +0x105
github.com/cometbft/cometbft/consensus.(*Handshaker).replayBlocks(_, {_, _}, {{{0xb, 0x1}, {0xc0008cd300, 0x6}}, {0xc0008cd310, 0xb}, 0x1, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:499 +0x23d
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x1}, {0xc0008cd300, 0x6}}, {0xc0008cd310, 0xb}, 0x1, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:410 +0x44d
github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc000050c90, {0x61d76a8, 0x88f6680}, {0x6204228?, 0xc00228e1c0?})
	/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:274 +0x478
github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x1}, {0xc0008cd300, 0x6}}, {0xc0008cd310, 0xb}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/node/setup.go:182 +0x1a9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x61d76a8, 0x88f6680}, 0xc0004b0780, {0x61c89e0, 0xc00212eb40}, 0xc0022da410, {0x61a25a0, 0xc002131770}, 0xc002159d01?, 0x5cdb450, ...)
	/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/node/node.go:350 +0x5b7
github.com/cometbft/cometbft/node.NewNode(0x0?, {0x61c89e0?, 0xc00212eb40?}, 0x0?, {0x61a25a0?, 0xc002131770?}, 0x0?, 0x0?, 0x0?, {0x61d77f8, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/cometbft/cometbft@v0.38.5/node/node.go:270 +0xa9
code.vegaprotocol.io/vega/core/blockchain/abci.NewTmNode({{0x0}, 0x1, 0x1, 0x0, 0x0, {0xc000cebc10, 0xa}, {{0x0}, {0xc000aad6e0, 0x15}}, ...}, ...)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/tm_node.go:100 +0x70a
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).startABCI(0xc000d54480, 0x0?, {0x6203ef8, 0xc0002f69e0}, {0x7ffe5839b037, 0x53}, {0x0?, 0x0?}, {0x0, 0x0})
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:431 +0x18a
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).startBlockchain(0xc000d54480, 0x0?, {0x7ffe5839b037?, 0x0?}, {0x0, 0x0}, {0x0, 0x0})
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:319 +0x39a
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1()
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:163 +0x88
created by code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run in goroutine 1
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:154 +0x710
```

### Observed behaviour

soak test failure

### Expected behaviour

no soak test failure

### Steps to reproduce

```bash
1. soak test failure can only be produced by running it along with another test on branch `fix-spot-trader-deposit` or on system-test develop
2.example https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/45656/
```

### Software version

dev branch

### Failing test

test_spot_update_proposal

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/45655/

**Comment by Sohill-Patel** [comment]
i can also reproduce the issue on system-test develop
https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/45656/

but strangely it did not occur in the nightly run
