### ISSUE TITLE
[Bug]: Panic in amend order

### ISSUE THREAD

**Issue by ze97286** [vegaprotocol/vega#10753]
### Problem encountered

```
panic: cannot amend order with remaining > potential sell

goroutine 1119006 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc01e6cd380?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc031f6c270, {0xc020a23980, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc01de30880?, {0x3d49873?, 0xc01ef66cc0?}, {0xc020a23980, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51
code.vegaprotocol.io/vega/core/positions.(*MarketPosition).AmendOrder(0xc0093993b0, 0xc0045502a0, 0xc01e435c70, 0x40?)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/positions/market_position.go:174 +0x558
code.vegaprotocol.io/vega/core/positions.(*Engine).AmendOrder(0xc00436ca00, {0x44563f8, 0xc0292b2570}, 0xc01e435c70, 0xc0279c7ad0)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/positions/engine.go:277 +0x397
code.vegaprotocol.io/vega/core/execution/future.(*Market).amendOrder(0xc0018d3200, {0x44563f8, 0xc0292b2570}, 0xc020a40720, {0xc01dbdb380, 0x40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3680 +0x1389
code.vegaprotocol.io/vega/core/execution/future.(*Market).AmendOrderWithIDGenerator(0xc0018d3200, {0x44563f8?, 0xc0292b2570}, 0xc020a40720, {0xc01dbdb380, 0x40}, {0x4426720?, 0xc020a328d0?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3426 +0x1bf
code.vegaprotocol.io/vega/core/execution.(*Engine).AmendOrder(0xc000c9ab00, {0x44563f8, 0xc0292b2570}, 0xc020a40720, {0xc01dbdb380, 0x40}, {0x4426720, 0xc020a328d0})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/engine.go:1110 +0x3a4
code.vegaprotocol.io/vega/core/processor.(*App).DeliverAmendOrder(0xc000ca9500, {0x44563f8, 0xc0292b2570}, {0x4482c60, 0xc0212b0cc0}, {0xc03a26f200, 0x40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:1770 +0x29b
code.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func25({0x44563f8, 0xc0292b2570}, {0x4482c60, 0xc0212b0cc0})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:542 +0x5e
code.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func26({0x44563f8, 0xc0292b2570}, {0x4482c60?, 0xc0212b0cc0?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:605 +0x5d
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc00057e180, {0xb8?, 0x392c840?}, 0xc01fc80000)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/abci/abci.go:173 +0x622
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0xc02d529ba8?, {0x44563c0?, 0x6899a60?}, 0xc000116e68?)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0xc0009865a0)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/nullchain.go:198 +0x4a4
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0xc0009865a0, 0x77359400)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/nullchain.go:275 +0x1ce
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/server.go:132 +0x25
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime in goroutine 1119004
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/server.go:131 +0x22f
```

### Observed behaviour

panic when trying to amend an order in the position engine. 

### Expected behaviour

no panic in amend order

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

develop

**Comment by ze97286** [comment]
the issue is with a FoK order that is submitted to the book and not matched - in which case it is unregistered from the position. The party is in isolated margin and isolated margin check fails, then the order is again unregistered from the position which leads to the position being disconnected from the orders.
