### ISSUE TITLE
panic: Failure after amend order from matching engine (amend-in-place)

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#10805]
Stacktrace 

```
goroutine 1748527 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x3?, 0x3?, {0x0?, 0x0?, 0xc021a9e0c0?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00aa36820, {0xc0445fe9c0, 0x3, 0x3})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc050fcdd80?, {0x3d7a9aa?, 0xc050995c00?}, {0xc0445fe9c0, 0x3, 0x3})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51
code.vegaprotocol.io/vega/core/execution/future.(*Market).orderAmendInPlace(0xc000a56600, 0xc02b947860, 0xc0508c6d00)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3975 +0x5aa
code.vegaprotocol.io/vega/core/execution/future.(*Market).amendOrder(0xc000a56600, {0x4460f38, 0xc038a02000}, 0xc01c6af980, {0xc066f37bc0, 0x40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3770 +0x1898
code.vegaprotocol.io/vega/core/execution/future.(*Market).AmendOrderWithIDGenerator(0xc000a56600, {0x4460f38?, 0xc038a02000}, 0xc01c6af980, {0xc066f37bc0, 0x40}, {0x4431240?, 0xc00e9028a0?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/future/market.go:3456 +0x1bf
code.vegaprotocol.io/vega/core/execution.(*Engine).AmendOrder(0xc00015b080, {0x4460f38, 0xc038a02000}, 0xc01c6af980, {0xc066f37bc0, 0x40}, {0x4431240, 0xc00e9028a0})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/execution/engine.go:1110 +0x3a4
code.vegaprotocol.io/vega/core/processor.(*App).DeliverAmendOrder(0xc000395c00, {0x4460f38, 0xc038a02000}, {0x448d7c0, 0xc00fe98c40}, {0xc048fde4c0, 0x40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:1770 +0x29b
code.vegaprotocol.io/vega/core/processor.NewApp.addDeterministicID.func25({0x4460f38, 0xc038a02000}, {0x448d7c0, 0xc00fe98c40})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:542 +0x5e
code.vegaprotocol.io/vega/core/processor.NewApp.(*App).SendTransactionResult.func26({0x4460f38, 0xc038a02000}, {0x448d7c0?, 0xc00fe98c40?})
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/processor/abci.go:605 +0x5d
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc00022c780, {0xb8?, 0x3934fe0?}, 0xc04dc6a000)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/abci/abci.go:173 +0x622
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0xc0100b3308?, {0x4460f00?, 0x68a8b20?}, 0xc00cc51e68?)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0xc000033680)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/nullchain.go:198 +0x4a4
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0xc000033680, 0x77359400)
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/nullchain.go:275 +0x1ce
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/server.go:132 +0x25
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime in goroutine 1748525
	/jenkins/workspace/common/vega-market-sim-reinforcement/extern/vega/core/blockchain/nullchain/server.go:131 +0x22f
```

Node.out: 
[data_node.out.txt](https://github.com/vegaprotocol/vega/files/14472559/data_node.out.txt)

Replay: (too big to attach).

**Comment by davidsiska-vega** [comment]
Dup of #10804
