### ISSUE TITLE
market sim vAMM / special orders / auction crash

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#11641]
All the stuff here https://jenkins.vega.rocks/job/common/job/vega-market-sim-fuzzing-develop/6/display/redirect

```
panic: re submit special order would cross

goroutine 88450 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc0068d3ae0?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc005648ea0, {0xc008e33880, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0x3480d3386cef0000?, {0x40af6d6?, 0x0?}, {0xc008e33880, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51
code.vegaprotocol.io/vega/core/matching.(*OrderBook).ReSubmitSpecialOrders(0xc003e25ea0, 0xc0035aa750)
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/matching/orderbook.go:942 +0x4fb
code.vegaprotocol.io/vega/core/execution/future.(*Market).reSubmitPeggedOrders(0xc00418e000, {0x486f058, 0xc0026e6ae0}, {0xc000847500, 0x12, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/execution/future/special_orders.go:112 +0xf3
code.vegaprotocol.io/vega/core/execution/future.(*Market).repriceAllSpecialOrders(0xc00418e000, {0x486f058, 0xc0026e6ae0}, 0xc0?, {0xc005884000?, 0xc000a7a710?, 0xc0041608c0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/execution/future/special_orders.go:151 +0x117
code.vegaprotocol.io/vega/core/execution/future.(*Market).checkForReferenceMoves(0xc00418e000, {0x486f058, 0xc0026e6ae0}, {0xc005884000, 0x122, 0x200}, 0x1)
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/execution/future/reference_price_moves.go:54 +0x2b1
code.vegaprotocol.io/vega/core/execution/future.(*Market).leaveAuction(0xc00418e000, {0x486f058?, 0xc0026e6ae0}, {0x0?, 0xedbec1b74?, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/execution/future/market.go:1825 +0x1314
code.vegaprotocol.io/vega/core/execution/future.(*Market).checkAuction(0xc00418e000, {0x486f058?, 0xc0026e6ae0}, {0x0?, 0xedbec13e8?, 0x0?}, {0x483dc80?, 0xc001bef3c8})
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/execution/future/auction.go:155 +0x103f
code.vegaprotocol.io/vega/core/execution/future.(*Market).OnTick(0xc00418e000, {0x486f058, 0xc0026e6ae0}, {0x40?, 0xc0074343e0?, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/execution/future/market.go:1091 +0x6d8
code.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0xc000d07c00, {0x486f058, 0xc0026e6ae0}, {0x1?, 0x488ee80?, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/execution/engine.go:1223 +0x4f1
code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/vegatime/service.go:111
code.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc000a7e180, {0x486f058, 0xc0026e6ae0}, {0x40?, 0x6e29a80?, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/vegatime/service.go:80 +0x263
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(0xc000a83180, 0xad5, {0xc003df2c80, 0x40}, {0xc00827bb00?, 0x453c69?, 0x0?}, {0x0, 0x0}, {0x6e29a80, ...})
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/processor/abci.go:1347 +0x976
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc0006bab40, {0xb8?, 0x3cbc860?}, 0xc001b40cc0)
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/blockchain/abci/abci.go:168 +0x449
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0xc00d4183d8?, {0x486f020?, 0x6e29a80?}, 0x3b9aca00?)
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0xc00065d8c0)
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/blockchain/nullchain/nullchain.go:212 +0x556
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0xc00065d8c0, 0x6c088e200)
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/blockchain/nullchain/nullchain.go:289 +0x1ce
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/blockchain/nullchain/server.go:132 +0x25
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime in goroutine 88432
	/jenkins/workspace/common/vega-market-sim-fuzzing-develop/extern/vega/core/blockchain/nullchain/server.go:131 +0x22f

```

**Comment by davidsiska-vega** [comment]
In fact this one is crashing too: https://jenkins.vega.rocks/job/common/job/vega-market-sim-fuzzing-release-candidate/10/display/redirect 

```
panic: re submit special order would cross

goroutine 38857 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc002a29220?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc002af7860, {0xc00a8d4380, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0x16636fb7b2560000?, {0x40af6f4?, 0x0?}, {0xc00a8d4380, 0x2, 0x2})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.25.0/logger.go:258 +0x51
code.vegaprotocol.io/vega/core/matching.(*OrderBook).ReSubmitSpecialOrders(0xc003c34960, 0xc0003d0a90)
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/matching/orderbook.go:945 +0x9b6
code.vegaprotocol.io/vega/core/execution/future.(*Market).reSubmitPeggedOrders(0xc003e04a80, {0x486eeb8, 0xc004a611a0}, {0xc00c103000, 0x5b, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/execution/future/special_orders.go:112 +0xf3
code.vegaprotocol.io/vega/core/execution/future.(*Market).repriceAllSpecialOrders(0xc003e04a80, {0x486eeb8, 0xc004a611a0}, 0x0?, {0xc00a8e4000?, 0xc00a8b8b50?, 0xc003e018c0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/execution/future/special_orders.go:151 +0x117
code.vegaprotocol.io/vega/core/execution/future.(*Market).checkForReferenceMoves(0xc003e04a80, {0x486eeb8, 0xc004a611a0}, {0xc00a8e4000, 0x18f, 0x200}, 0x1)
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/execution/future/reference_price_moves.go:54 +0x2b1
code.vegaprotocol.io/vega/core/execution/future.(*Market).leaveAuction(0xc003e04a80, {0x486eeb8?, 0xc004a611a0}, {0x0?, 0xedbec1589?, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/execution/future/market.go:1825 +0x1314
code.vegaprotocol.io/vega/core/execution/future.(*Market).checkAuction(0xc003e04a80, {0x486eeb8?, 0xc004a611a0}, {0x0?, 0xedbec13e5?, 0x0?}, {0x483dae0?, 0xc008350780})
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/execution/future/auction.go:155 +0x103f
code.vegaprotocol.io/vega/core/execution/future.(*Market).OnTick(0xc003e04a80, {0x486eeb8, 0xc004a611a0}, {0x40?, 0xc009146ee0?, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/execution/future/market.go:1091 +0x6d8
code.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0xc000f73880, {0x486eeb8, 0xc004a611a0}, {0x1?, 0x488ece0?, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/execution/engine.go:1223 +0x4f1
code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/vegatime/service.go:111
code.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc000f66100, {0x486eeb8, 0xc004a611a0}, {0x40?, 0x6e2ca20?, 0x0?})
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/vegatime/service.go:80 +0x263
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(0xc0006af180, 0x4ea, {0xc0090af540, 0x40}, {0xc00408db00?, 0x453c69?, 0x0?}, {0x0, 0x0}, {0x6e2ca20, ...})
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/processor/abci.go:1347 +0x976
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).FinalizeBlock(0xc00021a0c0, {0xb8?, 0x3cbc860?}, 0xc009024300)
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/blockchain/abci/abci.go:168 +0x449
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).FinalizeBlock(0xc008eb6f30?, {0x486ee80?, 0x6e2ca20?}, 0x3b9aca00?)
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/cmd/vega/commands/node/app_wrapper.go:91 +0x25
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0xc000407c20)
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/blockchain/nullchain/nullchain.go:212 +0x556
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0xc000407c20, 0x4e3b29200)
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/blockchain/nullchain/nullchain.go:289 +0x1ce
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/blockchain/nullchain/server.go:132 +0x25
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime in goroutine 38855
	/jenkins/workspace/common/vega-market-sim-fuzzing-release-candidate/extern/vega/core/blockchain/nullchain/server.go:131 +0x22f
```
