### ISSUE TITLE
Vega network sometimes fails to sign proposals after checkpoint restore

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#5958]
# Problem encountered
(Issue marked critical, since it a) results in a dead network and b) affects the smoke run used by all PRs)
Sometimes, the checkpoint tests fail (perhaps 1 in 5? 1 in 10? I don't have an exact number, but I think I've seen 4-5 instances this week) with an error like:
```
AssertionError: Network did not return epoch data in 60 seconds.
assert (None)
```
This error is caused by data node not being restored after checkpoint restore in one of the checkpoint tests, with the test logs reporting a whole bunch of:
```

[2022-08-19T15:44:02.785Z] 2022-08-19 15:44:02.670:[ERROR] MainProcess network.py:wait_for_network_ready:211 ----- Network not ready due to Data node RPC error.

[2022-08-19T15:44:02.785Z] Traceback (most recent call last):

[2022-08-19T15:44:02.785Z]   File "/workspace/modules/vegacapsule/network.py", line 200, in wait_for_network_ready

[2022-08-19T15:44:02.785Z]     timestamps = networkMod.get_api_epoch_data()["timestamps"]

[2022-08-19T15:44:02.785Z]   File "/workspace/modules/networkMod/networkMod.py", line 728, in get_api_epoch_data

[2022-08-19T15:44:02.785Z]     response = api.grpc_stub_trd_data_v2.GetEpoch(req)

[2022-08-19T15:44:02.785Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 923, in __call__

[2022-08-19T15:44:02.785Z]     return _end_unary_response_blocking(state, call, False, None)

[2022-08-19T15:44:02.785Z]   File "/usr/local/lib/python3.8/dist-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking

[2022-08-19T15:44:02.785Z]     raise _InactiveRpcError(state)

[2022-08-19T15:44:02.785Z] grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

[2022-08-19T15:44:02.785Z] 	status = StatusCode.INTERNAL

[2022-08-19T15:44:02.785Z] 	details = "Internal error"

[2022-08-19T15:44:02.785Z] 	debug_error_string = "{"created":"@1660923842.670588070","description":"Error received from peer ipv4:127.0.0.1:3027","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Internal error","grpc_status":13}"
```
as it waits for the network to revive after the checkpoint restore. An example job would be this one:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/1595/
In this case, there are no data node errors that look relevant (to my eye), but the vega logs include something like this:
```
2022-08-19T15:42:53.126Z	ERROR	tendermint	consensus/state.go:1163	propose step; failed signing proposal	{"height": 1, "round": 0, "err": "error signing proposal: height regression. Got 1, last height 34"}
2022-08-19T15:42:54.033Z	INFO	tendermint	p2p/switch.go:716	Dialing peer	{"address": "5d5dd0715bf476671aca02a80f939796f357a495@127.0.0.1:26626"}
2022-08-19T15:42:54.034Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting Peer service", "impl": "Peer{MConn{127.0.0.1:26626} 5d5dd0715bf476671aca02a80f939796f357a495 out}"}
2022-08-19T15:42:54.034Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting MConnection service", "impl": "MConn{127.0.0.1:26626}"}
2022-08-19T15:42:54.034Z	INFO	tendermint	p2p/switch.go:836	Added peer	{"peer": "Peer{MConn{127.0.0.1:26626} 5d5dd0715bf476671aca02a80f939796f357a495 out}"}
2022-08-19T15:42:56.124Z	INFO	tendermint	consensus/ticker.go:124	Timed out	{"dur": "3s", "height": 1, "round": 0, "step": "RoundStepPropose"}
2022-08-19T15:42:56.127Z	ERROR	tendermint	consensus/state.go:2251	failed signing vote	{"height": 1, "round": 0, "vote": "Vote{0:C19DE6AB0B35 1/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 000000000000 @ 2022-08-19T15:42:56.127176791Z}", "err": "error signing vote: height regression. Got 1, last height 34"}
```

# Observed behaviour
Data node sometimes does not come back after checkpoint restart. Vega log has proposal signing error

# Expected behaviour
Network restarts from checkpoint. Data node returns current epoch. Test passes.

# Steps to reproduce

## Automation
(Run PR system test pipeline, or manually trigger a job with "network_infra_smoke" marker. Locally, this can be achieved with:
pytest -m network_infra_smoke

# Evidence

## Logs
Logs from Jenkins run where this happened:
[archive.zip](https://github.com/vegaprotocol/vega/files/9384024/archive.zip)
Plus the test log, which is not saved in this archive:
[test_log.zip](https://github.com/vegaprotocol/vega/files/9384030/test_log.zip)

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment]
Closing as this issue is no longer being seen. If this returns we can re-=open this issue.
