### ISSUE TITLE
Starting from localsnapshot fails

### ISSUE THREAD

**Issue by mkjmdski** [vegaprotocol/vega#6108]
# Problem encountered
/home/vega/vegavisor_home/current/vega start --home /home/vega/vega_home --tendermint-home /home/vega/tendermint_home --nodewallet-passphrase-file /home/vega/vega_home/all-wallet-passphrase.txt --snapshot.load-from-block-height -1

on n01.devnet3.vega.xyz

# Observed behaviour
```
2022-09-08T15:14:02.614Z	INFO	root	node/node.go:95	starting vega	{"version": "v0.55.1+dev", "commit-hash": "dba76d1e8ec18396ed62bbff053af387f5ec96ba"}
2022-09-08T15:14:02.614Z	INFO	root	node/node.go:378	vega is starting with pprof profile, this is not a recommended setting for production
2022-09-08T15:14:06.933Z	INFO	spam	spam/engine.go:116	Spam protection started
2022-09-08T15:14:06.933Z	INFO	pow	pow/engine.go:98	PoW spam protection started
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:64	starting accounts core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:69	starting assets core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:74	starting network parameters core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:79	starting network limits core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:84	starting parties core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:89	starting validators core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:94	starting markets core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:99	starting proposals core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:104	starting marketsData core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:109	starting votes core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:114	starting parties stake core api
2022-09-08T15:14:06.933Z	INFO	coreapi	coreapi/service.go:119	starting delegations core api
2022-09-08T15:14:06.934Z	INFO	api.restproxy	rest/server.go:75	Starting REST<>GRPC based API	{"addr": "0.0.0.0", "port": 3003}
2022-09-08T15:14:06.934Z	INFO	admin.server	admin/server.go:111	Starting Server<>RPC based API	{"socket-path": "/tmp/vega.sock", "http-path": "/rpc"}
2022-09-08T15:14:06.934Z	INFO	admin.server	admin/server.go:143	Serving Server<>RPC based API
2022-09-08T15:14:06.934Z	INFO	api.grpc	api/grpc.go:230	Starting gRPC based API	{"addr": "0.0.0.0", "port": "3002"}
2022-09-08T15:14:06.978Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting multiAppConn service", "impl": "multiAppConn"}
2022-09-08T15:14:06.978Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting localClient service", "impl": "localClient"}
2022-09-08T15:14:06.978Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting localClient service", "impl": "localClient"}
2022-09-08T15:14:06.978Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting localClient service", "impl": "localClient"}
2022-09-08T15:14:06.978Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting localClient service", "impl": "localClient"}
2022-09-08T15:14:06.978Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting EventBus service", "impl": "EventBus"}
2022-09-08T15:14:06.978Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting PubSub service", "impl": "PubSub"}
2022-09-08T15:14:06.995Z	INFO	tendermint	service/service.go:139	service start	{"msg": "Starting IndexerService service", "impl": "IndexerService"}
2022-09-08T15:14:07.021Z	INFO	snapshot	snapshot/engine.go:329	loading snapshot for height	{"height": -1}
2022-09-08T15:14:07.021Z	PANIC	processor	processor/abci.go:428	failed to check if snapshot has been loaded	{"error": "failed to export iavl tree: appstate missing from tree"}
panic: failed to check if snapshot has been loaded

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005bb5c0, {0xc00012d9c0, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x44c
go.uber.org/zap.(*Logger).Panic(0xc000001860?, {0x246ad5d?, 0x1?}, {0xc00012d9c0, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.21.0/logger.go:230 +0x59
code.vegaprotocol.io/vega/core/processor.(*App).Info(0xc000ef8dc0, {{0x2c?, 0x2c?}, 0x411045?, 0xc0005252d0?})
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/core/processor/abci.go:428 +0x32b
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).Info(0xc00012c9c0?, {{0x2404b16?, 0x0?}, 0xc000525448?, 0x411045?})
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/core/blockchain/abci/abci.go:43 +0x6b
code.vegaprotocol.io/vega/cmd/vega/node.(*appW).Info(0x39a3f80?, {{0x2404b16?, 0xc000276d40?}, 0xc0005254c0?, 0xbe7ecd?})
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/cmd/vega/node/app_wrapper.go:37 +0x59
github.com/tendermint/tendermint/abci/client.(*localClient).InfoSync(0xc001006ba0, {{0x2404b16?, 0x93?}, 0xc000525590?, 0x4e42c6?})
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.21/abci/client/local_client.go:224 +0x107
github.com/tendermint/tendermint/proxy.(*appConnQuery).InfoSync(0x4e4204?, {{0x2404b16?, 0xc001016400?}, 0xc001016400?, 0xc000276d40?})
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.21/proxy/app_conn.go:155 +0x29
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000525a08, {0x2966d78, 0xc000262c30})
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.21/consensus/replay.go:244 +0x76
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2404b16, 0x7}}, {0xc000e42670, 0xe}, 0x1, 0x0, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.21/node/node.go:330 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000d55680, {0x2950140, 0xc0002b4aa0}, 0xc00115ee30, {0x293fd40, 0xc0005c92a8}, 0xc0010f80a0?, 0x41100e?, 0xc00115ef00, {0x29546d0, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.21/node/node.go:778 +0x597
code.vegaprotocol.io/vega/core/blockchain/abci.NewTmNode({{0x0}, 0x1, 0x1, 0x0, 0x0, {0xc001424ea0, 0xa}, {{0x0}, {0xc000133c68, 0x15}}, ...}, ...)
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/core/blockchain/abci/tm_node.go:78 +0x6a5
code.vegaprotocol.io/vega/cmd/vega/node.(*Command).startABCI(0xc00147c400, {0x3?, 0x0?}, {0x2964f60, 0xc0005317a0}, {0x7ffe582717d6, 0x1a}, {0x0?, 0x5?}, {0x0, ...})
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/cmd/vega/node/node.go:430 +0x169
code.vegaprotocol.io/vega/cmd/vega/node.(*Command).startBlockchain(0xc00147c400, {0x7ffe582717d6?, 0xc00059dce0?}, {0x0, 0x0}, {0x0, 0x0})
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/cmd/vega/node/node.go:315 +0x345
code.vegaprotocol.io/vega/cmd/vega/node.(*Command).Run(0xc00147c400, 0xc000036e00, {0x29648b8?, 0xc00142ae60}, {0xc0005abe40, 0x40}, {0x7ffe582717d6, 0x1a}, {0x0, 0x0}, ...)
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/cmd/vega/node/node.go:131 +0x597
main.(*StartCmd).Execute(0x3b7dae0, {0xc001431950, 0x0, 0x9})
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/cmd/vega/node.go:80 +0x6be
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc00059d200, {0xc00004e0b0, 0x9, 0x9})
	/jenkins/GOPATH/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x809
github.com/jessevdk/go-flags.(*Parser).Parse(...)
	/jenkins/GOPATH/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.Main({0x2955dc8, 0xc000052070})
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/cmd/vega/main.go:92 +0x53a
main.main()
	/jenkins/workspace/private/Deployments/Vegavisor/Devnet-3-Restart-Network/vega/cmd/vega/main.go:44 +0x27

```

# Expected behaviour
vega starts from snapshot instead of failing

**Comment by gordsport** [comment]
This will be addressed in: 
- https://github.com/vegaprotocol/vega/issues/5442
-
