### ISSUE TITLE
panic: Failed to process committed block - load test failure

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6371]
This run aborted prematurely with panic
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/11803/artifact/testnet/logs/testnet-nodeset-validators-3-validator/vega-validator-3.stderr-2022-09-30T04%3A01%3A33Z.log

There were three stderr outputs with panics, all at different times
16:44, 22:20 and 04:01 (30.9)

```
panic: Failed to process committed block (37502:135F5481D5364853C57828D1DA0DDA09B8487BB0EFA138AE232F1DED62DAF7EE): leveldb: closed

goroutine 230 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc001642700, 0x0)
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.21/blockchain/v0/reactor.go:407 +0x12da
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.21/blockchain/v0/reactor.go:110 +0x7a
```

**Comment by vega-paul** [comment]
new run 
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/12558/
