### ISSUE TITLE
panic: settlement balance is not zero

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/vega#6375]
Running RL learning from `[9f1e624](https://github.com/vegaprotocol/vega-market-sim/pull/185/commits/9f1e6244059e23efb2fe79c96863bb2dafc17b54)` draft PR: https://github.com/vegaprotocol/vega-market-sim/pull/185 with `python ./vega_sim/reinforcement/run_rl_agent.py --rl-max-it 1000` (which took most of a day on my computer; I know I am not making any friends here. 

Fails randomly (once in iteration 693, second time in 938) with 
```
panic: settlement balance is not zero

goroutine 32686897 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x140260012c0, {0x14022b36940, 0x1, 0x1})
	/Users/davidsiska/go/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x30c
go.uber.org/zap.(*Logger).Panic(0x1?, {0x101d93c7c?, 0x0?}, {0x14022b36940, 0x1, 0x1})
	/Users/davidsiska/go/pkg/mod/go.uber.org/zap@v1.21.0/logger.go:230 +0x54
code.vegaprotocol.io/vega/core/collateral.(*Engine).FinalSettlement(0x140015623f0, {0x10296dc00, 0x14019481710}, {0x14018336480, 0x40}, {0x140194817d0, 0x6, 0x6})
	/Users/davidsiska/git-repos/github.com/vegaprotocol/vega-market-sim/extern/vega/core/collateral/engine.go:737 +0x184c
code.vegaprotocol.io/vega/core/execution.(*Market).closeMarket(0x1401a096b40, {0x10296dc00, 0x14019481710}, {0x0?, 0x14019c93f68?, 0x0?})
```

Full node error log: 
[node.err.txt](https://github.com/vegaprotocol/vega/files/9695205/node.err.txt)

Last 20k lines from node output log: [node.out.tail-n20000.txt](https://github.com/vegaprotocol/vega/files/9695208/node.out.tail-n20000.txt)

**Comment by davidsiska-vega** [comment]
I can do a bunch of things to help debug this; perhaps run with @TomMcL  transaction recording... let me know @jeremyletang or whoever ends up picking this up.
