### ISSUE TITLE
Consensus failure on staging 1 with last release

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#6764]
```
Nov 09 15:39:37 n01.stagnet1.vega.xyz visor[2036980]: 2022-11-09T15:39:37.546Z        ERROR        tendermint        consensus/state.go:727        CONSENSUS FAILURE!!!        {"err": "unknown subscriber ID 32", "stack": "goroutine 346 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:727 +0x4c\npanic({0x2bbb640, 0xc007152040})\n\t/opt/hostedtoolcache/go/1.19.2/x64/src/runtime/panic.go:884 +0x212\ncode.vegaprotocol.io/vega/core/oracles.(*specSubscriptions).removeSubscriber(0xc000524880, 0x20)\n\t/home/runner/work/vega/vega/core/oracles/engine_subscribers.go:160 +0x4e5\ncode.vegaprotocol.io/vega/core/oracles.(*Engine).Unsubscribe(0xc001fd8e10, {0x3be76a0, 0xc020bea120}, 0x1?)\n\t/home/runner/work/vega/vega/core/oracles/engine.go:146 +0x4d\ncode.vegaprotocol.io/vega/core/oracles.(*Engine).Subscribe.func1({0x3be76a0?, 0xc020bea120?}, 0x3?)\n\t/home/runner/work/vega/vega/core/oracles/engine.go:139 +0x33\ncode.vegaprotocol.io/vega/core/products.(*Future).UnsubscribeTradingTerminated(0xc005057c20, {0x3be76a0, 0xc020bea120})\n\t/home/runner/work/vega/vega/core/products/future.go:49 +0x16e\ncode.vegaprotocol.io/vega/core/execution.(*Market).tradingTerminated(0xc003dfcb40, {0x3be76a0, 0xc020bea120}, 0x8?)\n\t/home/runner/work/vega/vega/core/execution/market.go:3129 +0xe8\ncode.vegaprotocol.io/vega/core/products.(*Future).setTradingTerminated(0x0?, {0x3be76a0?, 0xc020bea120?}, 0x80?, {0x0?, 0x0?})\n\t/home/runner/work/vega/vega/core/products/future.go:202 +0x1a8\ncode.vegaprotocol.io/vega/core/products.(*Future).updateTradingTerminatedByTimestamp(0xc005057c20, {0x3be76a0, 0xc020bea120}, {{0x0?, 0xc00b3ee240?, 0xc039ec52c8?}, 0xc020bea180?})\n\t/home/runner/work/vega/vega/core/products/future.go:188 +0xe6\ncode.vegaprotocol.io/vega/core/oracles.(*Engine).BroadcastData(0xc001fd8e10, {0x3be76a0, 0xc020bea120}, {{0x0?, 0x1?, 0x2cd6ca0?}, 0xc020bea180?})\n\t/home/runner/work/vega/vega/core/oracles/engine.go:117 +0x7aa\ncode.vegaprotocol.io/vega/core/oracles.(*Builtin).OnTick(0xc000e63030, {0x3be76a0, 0xc020bea120}, {0x1?, 0x3bfdfa0?, 0x0?})\n\t/home/runner/work/vega/vega/core/oracles/builtin.go:50 +0x165\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)\n\t/home/runner/work/vega/vega/core/vegatime/service.go:104\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc001462280, {0x3be76a0, 0xc020bea120}, {0x40?, 0x2bbac00?, 0x0?})\n\t/home/runner/work/vega/vega/core/vegatime/service.go:77 +0x24f\ncode.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0xc00c7c8680, 0x20, 0x20}, {{0xb, 0x1}, {0xc009b9d060, 0x1a}, 0x17606, {0x1ceccf9a, ...}, ...}, ...})\n\t/home/runner/work/vega/vega/core/processor/abci.go:774 +0x730\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0xc00c7c8680, 0x20, 0x20}, {{0xb, 0x1}, {0xc009b9d060, 0x1a}, 0x17606, {0x1ceccf9a, ...}, ...}, ...})\n\t/home/runner/work/vega/vega/core/blockchain/abci/abci.go:46 +0x75\ncode.vegaprotocol.io/vega/cmd/vega/node.(*appW).BeginBlock(_, {{0xc00c7c8680, 0x20, 0x20}, {{0xb, 0x1}, {0xc009b9d060, 0x1a}, 0x17606, {0x1ceccf9a, ...}, ...}, ...})\n\t/home/runner/work/vega/vega/cmd/vega/node/app_wrapper.go:68 +0x55\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc00c7c8680, 0x20, 0x20}, {{0xb, 0x1}, {0xc009b9d060, 0x1a}, 0x17606, {0x1ceccf9a, ...}, ...}, ...})\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:280 +0x118\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc00c7c8680, 0x20, 0x20}, {{0xb, 0x1}, {0xc009b9d060, 0x1a}, 0x17606, {0x1ceccf9a, ...}, ...}, ...})\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:81 +0x55\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x3be5de8?, 0xc00052ef90}, {0x3bf7c90, 0xc001b0bc20}, 0xc003dfcf00, {0x3c08120, 0xc000564588}, 0x17605?)\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/state/execution.go:307 +0x3dd\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc001062088, 0x7}}, {0xc001fa1b80, 0x1a}, 0x1, 0x17605, {{0xc01cebd2e0, ...}, ...}, ...}, ...)\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/state/execution.go:140 +0x171\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc00387e000, 0x17606)\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:1659 +0xafd\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc00387e000, 0x17606)\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:1568 +0x2ff\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:1503 +0x94\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc00387e000, 0x17606, 0x0)\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:1541 +0xccf\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc00387e000, 0xc008e7cfa0, {0xc0038a12f0, 0x28})\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:2155 +0x18dc\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc00387e000, 0xc008e7cfa0, {0xc0038a12f0?, 0xc006933f00?})\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:1953 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc00387e000, {{0x3bc5c80?, 0xc005cff8b8?}, {0xc0038a12f0?, 0x0?}})\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:856 +0x170\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc00387e000, 0x0)\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:763 +0x3f9\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.22/consensus/state.go:379 +0x12d\n"}
```

**Comment by ze97286** [comment]
The issue here is the following:
1. Market is terminated
2. The market is updated with a time based oracle, we subscribe to the oracle
3. The market is updated again with another time based oracle but with the same id, we subscribe to that one and not remove the other subscription.
4. the earlier of the time termination ticks, we unsubscribe it
5. the latter of the time termination ticks we unsubscribe it but the subscription  has the same id as the one we've already removed in (4) so we panic.
