### ISSUE TITLE
failed to reprovide: failed to find any peer in table panic: context cancelled whilst waiting for create snapshot lock

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#6807]
Local snapshot panic in VC

```
2022-11-14T09:40:03.097Z	ERROR	reprovider.simple	simple/reprovide.go:109	failed to reprovide: failed to find any peer in table
panic: context cancelled whilst waiting for create snapshot lock

goroutine 556 [running]:
code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*Service).CreateSnapshot(0xc001218d10, {0x4872d98?, 0xc00375c600}, {0xc00230c840, 0x7}, 0x723, 0x738)
	/Users/paulwebb/repos/vega/datanode/dehistory/snapshot/service_create_snapshot.go:56 +0x130f
code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*Service).SnapshotData(0xc0016fd58c?, {0x4872d98?, 0xc00375c600?}, {0xc00230c840?, 0x8000000000000000?}, 0xedb03fff2?, 0x66811c0?)
	/Users/paulwebb/repos/vega/datanode/dehistory/snapshot/service.go:47 +0x5c
code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*BlockCommitHandler).OnBlockCommitted(0xc00455c0b0, {0x4872d98, 0xc00375c600}, {0xc00230c840, 0x7}, 0x738)
	/Users/paulwebb/repos/vega/datanode/dehistory/snapshot/block_commit_handler.go:67 +0x29e
code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).Receive(0xc0019e2000, {0x4872d98, 0xc00375c600})
	/Users/paulwebb/repos/vega/datanode/broker/sqlstore_broker.go:129 +0x197
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func5()
	/Users/paulwebb/repos/vega/cmd/data-node/commands/start/node.go:122 +0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/Users/paulwebb/Projects/go/pkg/mod/golang.org/x/sync@v0.0.0-20220929204114-8fcdb60fdcc0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/paulwebb/Projects/go/pkg/mod/golang.org/x/sync@v0.0.0-20220929204114-8fcdb60fdcc0/errgroup/errgroup.go:72 +0xa5
```

**Comment by vega-paul** [comment]
[data_node_full.tmpl.txt](https://github.com/vegaprotocol/vega/files/10002060/data_node_full.tmpl.txt)
[data_node_full_multi_db.tmpl.txt](https://github.com/vegaprotocol/vega/files/10002061/data_node_full_multi_db.tmpl.txt)

**Comment by gordsport** [comment]
@vega-paul 
To turn off on the system test run and leave running on network-infra runs as this will affect STs as mainnet will have an interval of 100 blocks so this issue should not be seen

**Comment by gordsport** [comment]
Closing as its a system tests issue - now covered in: 
- https://github.com/vegaprotocol/system-tests/issues/1455
