### ISSUE TITLE
Data node can panic creating snapshot on network start

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#6877]
# Problem encountered
The protocol upgrade tests add a bunch for network resets (should be an entirely new network each time, new ganache, new database) and (once so far) I've seen a restart result in a panic, like so:
```
2022-11-18T18:44:47.857Z	PANIC	deHistory.snapshot	snapshot/service_create_snapshot.go:95	failed to snapshot data	{"error": "failed to copy table data:failed to execute copy copy (select * from chain order by onerow_check) to '/jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/data/node5/state/data-node/dehistory/snapshotscopyto/testnet-22-currentstatesnapshot/chain': ERROR: could not open file \"/jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/data/node5/state/data-node/dehistory/snapshotscopyto/testnet-22-currentstatesnapshot/chain\" for writing: No such file or directory (SQLSTATE 58P01)"}
panic: failed to snapshot data

goroutine 1449 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc002da8180?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc034feaa90, {0xc00467d100, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc0019922f0?, {0x4ab88af?, 0x16?}, {0xc00467d100, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:251 +0x59
code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*Service).CreateSnapshot.func5()
	/jenkins/workspace/common/system-tests-wrapper/vega/datanode/dehistory/snapshot/service_create_snapshot.go:95 +0x2da
created by code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*Service).CreateSnapshot
	/jenkins/workspace/common/system-tests-wrapper/vega/datanode/dehistory/snapshot/service_create_snapshot.go:91 +0xb33
block height on begin block, 23, is too high, the height of the last processed block is 0
Error: maximum number of possible restarts has been reached: failed to execute binary /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/visor/visor5/current/vega [datanode node --home /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/data/node5]: exit status 255
Usage:
  vegavisor run [flags]

Flags:
  -h, --help          help for run
      --home string   Path to visor home folder
```
Currently looking to see if I can reproduce this...

# Observed behaviour
Data node can die when a fresh network starts.

# Expected behaviour
Data node (and vega) all start and run without error.

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Automation
Run the "Nightly" system tests run on Jenkins, with the protocol_upgrade branch.

# Evidence
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28003/artifact/testnet/logs/testnet-nodeset-full-5-full/visor-5-with-vega-data-node.stdout-2022-11-18T18%3A44%3A26Z.log
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28003/artifact/testnet/logs/testnet-nodeset-full-5-full/visor-5-with-vega-data-node.stderr-2022-11-18T18%3A44%3A26Z.log

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by jgsbennett** [comment]
This seems to follow the following error from vegacapsule during multisig setup:
```
[2022-11-21T11:37:30.777Z] 2022-11-21 11:37:28.924:[INFO] [MainProcess] [MainThread] [   commands.py]:[multisig_init]:[ 266] Error: failed to verify signer: 0xEe7D375bcB50C26d52E1A4a472D8822A2A22d94F is not valid signer of messages
[2022-11-21T11:37:30.777Z] Usage:
[2022-11-21T11:37:30.777Z]   /jenkins/workspace/common/system-tests-wrapper/system-tests/vegacapsule-bin ethereum multisig init [flags]
[2022-11-21T11:37:30.777Z] 
[2022-11-21T11:37:30.777Z] Flags:
[2022-11-21T11:37:30.777Z]   -h, --help   help for init
[2022-11-21T11:37:30.777Z] 
[2022-11-21T11:37:30.777Z] Global Flags:
[2022-11-21T11:37:30.777Z]       --home-path string   Specify the location of network home directory (default "/home/ubuntu/.vegacapsule/testnet")
[2022-11-21T11:37:30.777Z]       --timeout uint       Specify the number of second to wait (default 60)
[2022-11-21T11:37:30.777Z] 
```
This reproduces at the same point in the test run on a retry.

**Comment by jgsbennett** [comment]
Usually we get this:
```
[2022-11-18T18:41:20.833Z] 2022-11-18 18:41:15.343:[INFO] [MainProcess] [MainThread] [   commands.py]:[multisig_init]:[ 262] /jenkins/workspace/common/system-tests-wrapper/system-tests/vegacapsule-bin ethereum multisig init --home-path /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet
[2022-11-18T18:41:26.410Z] 2022-11-18 18:41:26.338:[INFO] [MainProcess] [MainThread] [   commands.py]:[multisig_init]:[ 265] 
[2022-11-18T18:41:26.410Z] 2022-11-18 18:41:26.338:[INFO] [MainProcess] [MainThread] [   commands.py]:[multisig_init]:[ 266] 2022/11/18 18:41:15 Current multisig threshold: 500
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:15 Computed signature for set_threshold to 1: 0xe9f852328a9b345acb1708470d623c352ed137b36eb91f48091b534b84f29e016cd978382228bbc4edf6f0bffaada65030782e0225a885f0fde1d27a93c2f94001
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:16 Updated multisig threshold: 1
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:16 Number of signers for multisig: 1
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:16 Computed signature for add_signer for 0xCE689b0C330D39C82d0e947975EC3065120401A3: 0x3653f8244035537e2925f55a1cec098c9f0a2a91b127ea97dfcd25b4d74b4bd6400811da73b46a5488c6c703aa35db0d68b055db71a6061c60bcc6e6b061e54001
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:18 Added 0xCE689b0C330D39C82d0e947975EC3065120401A3 as a multisig validator
...
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:23 Computed signature for remove_signer for 0xEe7D375bcB50C26d52E1A4a472D8822A2A22d94F: 0xbf6c9c985228979bcd1799aa0179cf6fde4a6d1ceddc6a69183863ccb651d1721a5de92433ce04d068bfdd85e3dfe7318f61708998f8b4a9d944f747d3e0abe500
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:24 Removed the 0xEe7D375bcB50C26d52E1A4a472D8822A2A22d94F signer from multisig control
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:24 Updated number of signers for multisig: 5
...
[2022-11-18T18:41:26.410Z] 2022/11/18 18:41:26 Updated multisig threshold: 667
[2022-11-18T18:41:26.410Z] 
```
... but in this case (and I'm struggling to see anything important in the preamble that ought to be different), we get the error above...

**Comment by jgsbennett** [comment]
As an update, @karlem and I have somewhat satisfied ourselves that this looks like a bug in vegacapsule, where vegacapsule loses track of the non-vega-node tasks at a certain point in the run, and therefore does not stop those nodes when asked, causing all of the above. We'll likely need to either move this ticket to that repo, or close and open a new one over there.
