### ISSUE TITLE
panic: context cancelled whilst waiting for create snapshot lock

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6879]
There has been a panic observed in testnet related to datanode snapshots

discussion seen here: https://vegaprotocol.slack.com/archives/CEE07A084/p1669033852403439

```
panic: context cancelled whilst waiting for create snapshot lock
goroutine 589 [running]:
code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*Service).CreateSnapshot(0xc001e88840, {0x3be8ab8?, 0xc0034aa1c0}, {0xc001f37860, 0x1c}, 0xcfc39, 0xd0020)
        /home/runner/work/vega/vega/datanode/dehistory/snapshot/service_create_snapshot.go:56 +0x130f
code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*Service).SnapshotData(0xc0037d7c00?, {0x3be8ab8?, 0xc0034aa1c0?}, {0xc001f37860?, 0x8000000000000000?}, 0xedb006b0>
        /home/runner/work/vega/vega/datanode/dehistory/snapshot/service.go:47 +0x5c
code.vegaprotocol.io/vega/datanode/dehistory/snapshot.(*BlockCommitHandler).OnBlockCommitted(0xc000f52b00, {0x3be8ab8, 0xc0034aa1c0}, {0xc001f37860, 0x1c}, 0xd0020)
        /home/runner/work/vega/vega/datanode/dehistory/snapshot/block_commit_handler.go:67 +0x29e
code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).Receive(0xc001454360, {0x3be8ab8, 0xc0034aa1c0})
        /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:129 +0x197
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func5()
        /home/runner/work/vega/vega/cmd/data-node/commands/start/node.go:122 +0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:72 +0xa5
```

**Comment by ettec** [comment]
context time out was being hit due to this issue-> https://github.com/vegaprotocol/vega/issues/6945  
Now fixed
