### ISSUE TITLE
Panic received during starting datanodes

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7005]
Running against the below branches:

vega - `dehistory-failed-to-get-analysis`
vegacapsule - `add-swarm-key-support`
systemtests - `fix_datanpode_swarmkey_config`

Jenkins Run:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31719/

Received Panic:

```
panic: could not find validator set for height #1252

goroutine 503 [running]:
github.com/tendermint/tendermint/state.getBeginBlockValidatorInfo(0xc0011101e0, {0x5309028, 0xc001f59560}, 0x1)
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.24/state/execution.go:346 +0x3ea
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x52e7068?, 0xc000e88710}, {0x52f8780, 0xc000323830}, 0xc0011101e0, {0x5309028, 0xc001f59560}, 0x4e4?)
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.24/state/execution.go:293 +0x219
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0x49559f6, 0x7}}, {0xc00159e8b8, 0x7}, 0x1, 0x4e4, {{0xc00f34b360, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.24/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000e47340, 0x1)
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:400 +0xbda
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:127 +0xe5
```

Jenkins Error Log:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31719/artifact/testnet/logs/testnet-nodeset-full-9-full/vega-full-9.stderr-2022-12-01T13%3A42%3A52Z.log/*view*/

**Comment by wwestgarth** [comment]
I think the error pasted above isn't the true error and is just another tendermint bug not being able to handle shutting down gracefully.

In the test output its node 10 that causes the assertion, and the cleanup is just killing node9 (and thus the TM panic):
```
new_datanode.wait_until_ready()
new_dehistory_datanode.wait_until_ready()
```

The true error is in node 10:
```
problem starting blockchain	{"error": "failed to create new Tendermint node: invalid address (266106): strconv.ParseUint: parsing \"266106\": value out of range"}
```

which looks to be a capsule issue with mapping the ports in the template.
