### ISSUE TITLE
Panic in Market Sim testing run auction checks

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/vega#7036]
During Market Sim shadow tests we seem to have hit a core error which is throwing a panic. Transactions on the null chain path should now be taking the same validation route as those from Tendermint so probably shouldn't be able to reach the stage of causing a panic from Core. 

The error is below and the replay file is attached. Additionally whilst kept by Jenkins the files can be found [here](https://jenkins.ops.vega.xyz/job/common/job/vega-market-sim/997/artifact/test_logs/2022-12-05_114208-integration/vega-sim-zdzds7ih/)
[replay.zip](https://github.com/vegaprotocol/vega/files/10154847/replay.zip)

```
panic: re submit special order would cross

goroutine 99851 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc001d116e0?})
	/go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc011bf3d40, {0xc01205a400, 0x2, 0x2})
	/go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0x5f809bc?, {0x343ad2d?, 0x0?}, {0xc01205a400, 0x2, 0x2})
	/go/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:251 +0x59
code.vegaprotocol.io/vega/core/matching.(*OrderBook).ReSubmitSpecialOrders(0xc00db75860, 0xc00ff9ba40)
	/extern/vega/core/matching/orderbook.go:807 +0x69a
code.vegaprotocol.io/vega/core/execution.(*Market).reSubmitPeggedOrders(0xc00d352400, {0x3be5e40, 0xc017100a20}, {0xc01205a380, 0xa, 0x100?})
	/extern/vega/core/execution/special_orders.go:110 +0xfa
code.vegaprotocol.io/vega/core/execution.(*Market).repriceAllSpecialOrders(0xc00d352400, {0x3be5e40, 0xc017100a20}, 0x80?, {0xc01205a300, 0xd, 0x10})
	/extern/vega/core/execution/special_orders.go:167 +0x45e
code.vegaprotocol.io/vega/core/execution.(*Market).checkForReferenceMoves(0xc00d352400, {0x3be5e40, 0xc017100a20}, {0xc01205a300, 0xd, 0x10}, 0x1)
	/extern/vega/core/execution/reference_price_moves.go:79 +0x305
code.vegaprotocol.io/vega/core/execution.(*Market).leaveAuction(0xc00d352400, {0x3be5e40, 0xc017100a20}, {0xf710890?, 0xed936b190?, 0x0?})
	/extern/vega/core/execution/market.go:1140 +0xdeb
code.vegaprotocol.io/vega/core/execution.(*Market).checkAuction(0xc00d352400, {0x3be5e40, 0xc017100a20}, {0xf710890?, 0xed936b18f?, 0x0?})
	/extern/vega/core/execution/auction.go:112 +0x925
code.vegaprotocol.io/vega/core/execution.(*Market).OnTick(0xc00d352400, {0x3be5e40, 0xc017100a20}, {0x0?, 0x0?, 0x0?})
	/extern/vega/core/execution/market.go:729 +0x6b9
code.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0xc000f98e00, {0x3be5e40, 0xc017100a20}, {0x1?, 0x3bfbdc0?, 0x0?})
	/extern/vega/core/execution/engine.go:778 +0x253
code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
	/extern/vega/core/vegatime/service.go:104
code.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc001eb8d00, {0x3be5e40, 0xc017100a20}, {0x54ebb20?, 0x2bd6960?, 0x0?})
	/extern/vega/core/vegatime/service.go:77 +0x24f
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0xc011bbeb60, 0x20, 0x20}, {{0x0, 0x0}, {0xc001d4fda0, 0x6}, 0x243, {0xf710890, ...}, ...}, ...})
	/extern/vega/core/processor/abci.go:791 +0x730
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0xc011bbeb60, 0x20, 0x20}, {{0x0, 0x0}, {0xc001d4fda0, 0x6}, 0x243, {0xf710890, ...}, ...}, ...})
	/extern/vega/core/blockchain/abci/abci.go:46 +0x75
code.vegaprotocol.io/vega/cmd/vega/node.(*appW).BeginBlock(_, {{0xc011bbeb60, 0x20, 0x20}, {{0x0, 0x0}, {0xc001d4fda0, 0x6}, 0x243, {0xf710890, ...}, ...}, ...})
	/extern/vega/cmd/vega/node/app_wrapper.go:68 +0x55
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).BeginBlock(0xc000ea5e60)
	/extern/vega/core/blockchain/nullchain/nullchain.go:337 +0x399
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).processBlock(0xc000ea5e60)
	/extern/vega/core/blockchain/nullchain/nullchain.go:196 +0x247
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).ForwardTime(0xc000ea5e60, 0x3b9aca00)
	/extern/vega/core/blockchain/nullchain/nullchain.go:273 +0x1e5
code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime.func1()
	/extern/vega/core/blockchain/nullchain/server.go:129 +0x2a
created by code.vegaprotocol.io/vega/core/blockchain/nullchain.(*NullBlockchain).handleForwardTime
	/extern/vega/core/blockchain/nullchain/server.go:128 +0x24a
```

**Comment by TomMcL** [comment]
[replay.zip](https://github.com/vegaprotocol/vega/files/10154852/replay.zip)

**Comment by jeremyletang** [comment]
closing for now as we won't be able to reproduce with the recent changes of LPs.
