### ISSUE TITLE
panic: unable to reject market

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#7195]
# Problem encountered
Stagnet 1 run into `CONSENSUS FAILURE: unable to reject market` problem. This is `v0.65.0` version.

# Observed behaviour
The network has stopped processing blocks, cos of the consensus failure.

# Expected behaviour
There should not be a consensus failure error.

# Evidence

## Logs
```
Dec 21 12:44:36 n01.stagnet1.vega.xyz visor[3103673]: 2022-12-21T12:44:36.250Z        ERROR        tendermint        consensus/state.go:724        
CONSENSUS FAILURE!!!        {"err": "unable to reject market", "stack": "goroutine 383 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:724 +0x4c
panic({0x2c220e0, 0xc0063e8130})
	/opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x212
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x2?, {0x0?, 0x0?, 0xc00a574480?})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00b65ec30, {0xc008ac2f80, 0x2, 0x2})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.23.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc000f20e00?, {0x346586b?, 0xc00e8391d0?}, {0xc008ac2f80, 0x2, 0x2})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.23.0/logger.go:251 +0x59
code.vegaprotocol.io/vega/core/processor.(*App).onTick(0xc001ae42c0, {0x3c55518, 0xc00e8391d0}, {0x1?, 0x3c6c9e0?, 0x0?})
	/home/runner/work/vega/vega/core/processor/abci.go:1601 +0x59b
code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
	/home/runner/work/vega/vega/core/vegatime/service.go:104
code.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc000ea8780, {0x3c55518, 0xc00e8391d0}, {0x40?, 0x2c216a0?, 0x0?})
	/home/runner/work/vega/vega/core/vegatime/service.go:77 +0x24f
code.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0xc00a86a400, 0x20, 0x20}, {{0xb, 0x1}, {0xc01917bb40, 0x1a}, 0x18abe, {0x15f454be, ...}, ...}, ...})
	/home/runner/work/vega/vega/core/processor/abci.go:787 +0x747
code.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0xc00a86a400, 0x20, 0x20}, {{0xb, 0x1}, {0xc01917bb40, 0x1a}, 0x18abe, {0x15f454be, ...}, ...}, ...})
	/home/runner/work/vega/vega/core/blockchain/abci/abci.go:46 +0x75
code.vegaprotocol.io/vega/cmd/vega/node.(*appW).BeginBlock(_, {{0xc00a86a400, 0x20, 0x20}, {{0xb, 0x1}, {0xc01917bb40, 0x1a}, 0x18abe, {0x15f454be, ...}, ...}, ...})
	/home/runner/work/vega/vega/cmd/vega/node/app_wrapper.go:64 +0x55
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc00a86a400, 0x20, 0x20}, {{0xb, 0x1}, {0xc01917bb40, 0x1a}, 0x18abe, {0x15f454be, ...}, ...}, ...})
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc00a86a400, 0x20, 0x20}, {{0xb, 0x1}, {0xc01917bb40, 0x1a}, 0x18abe, {0x15f454be, ...}, ...}, ...})
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x3c53b10?, 0xc0001a9430}, {0x3c66000, 0xc0018bbc10}, 0xc0054dd680, {0x3c77080, 0xc000125dd0}, 0x18abd?)
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc0122aa080, 0x7}}, {0xc0045f9c20, 0x1a}, 0x1, 0x18abd, {{0xc00e3ba0e0, ...}, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/state/execution.go:140 +0x171
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc004c66000, 0x18abe)
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:1654 +0xafd
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc004c66000, 0x18abe)
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:1563 +0x2ff
github.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:1498 +0x94
github.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc004c66000, 0x18abe, 0x0)
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:1536 +0xccf
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc004c66000, 0xc008593f40, {0xc00463a7e0, 0x28})
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:2150 +0x18dc
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc004c66000, 0xc008593f40, {0xc00463a7e0?, 0xc007d4db00?})
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:1948 +0x2c
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc004c66000, {{0x3c32960?, 0xc00746d408?}, {0xc00463a7e0?, 0x0?}})
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:853 +0x170
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc004c66000, 0x0)
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:760 +0x3f9
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
	/home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/state.go:379 +0x12d
"}
```

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by davidsiska-vega** [comment]
At the risk of stating the obvious: It shouldn’t be possible to terminate a market before it was enacted - the termination trigger is part of the proposal which hasn’t yet been accepted via governance. So it can’t be terminated using a trigger that’s not agreed yet.
