### ISSUE TITLE
Panic in a snapshot engine during a startup

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7287]
# Problem encountered
A problem occurred when I was trying to start the network from a checkpoint.

# Observed behaviour

Network is not starting

# Expected behaviour

Network should not panic

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps I did attached in the first comment

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs

```
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: 2023-01-09T20:15:51.396Z        INFO        pprof        pprof/pprof.go:197        saving pprof cpu profile        {"path": "/home/vega/pprof/vega/pprof/cpu-2023-01-09-20-15-42.>
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: 2023-01-09T20:15:51.615Z        INFO        root        node/node.go:225        Vega shutdown complete        {"version": "v0.66.1", "version-hash": "93bd617abcf4ce5f2f3581efe02>
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: 2023-01-09T20:15:51.615Z        INFO        root        protocol/protocol.go:146        Stopping protocol services
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: 2023-01-09T20:15:51.615Z        INFO        event-forwarder        evtforward/engine.go:146        Stopping the Ethereum Event Forwarder
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: panic: runtime error: invalid memory address or nil pointer dereference [recovered]
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         panic: runtime error: invalid memory address or nil pointer dereference
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x120de56]
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: goroutine 150 [running]:
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/cmd/vega/node.(*Command).Run.func1.1()
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/cmd/vega/node/node.go:137 +0x59
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: panic({0x2d463e0, 0x56fd7b0})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /opt/hostedtoolcache/go/1.19.4/x64/src/runtime/panic.go:884 +0x212
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/validators.(*ERC20Signatures).RestorePendingSignatures(0xc0139c7aa0, 0x0)
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/validators/signatures_snapshot.go:53 +0x36
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/validators.(*Topology).restore(0xc0003c7dc0, {0x3c29c78, 0xc004d059e0}, 0xc004c84240, 0xc004c50ac0)
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/validators/topology_snapshot.go:326 +0x136a
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/validators.(*Topology).LoadState(0x2d164e0?, {0x3c29c78, 0xc004d059e0}, 0xc004c50ac0)
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/validators/topology_snapshot.go:207 +0xa5
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/snapshot.(*Engine).applySnap(0xc001542000, {0x3c29bd0, 0xc001e40240})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/snapshot/engine.go:610 +0xdd4
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/snapshot.(*Engine).applySnapshotFromLocalStore(0xc001542000, {0x3c29bd0, 0xc001e40240})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/snapshot/engine.go:500 +0x7e
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/snapshot.(*Engine).CheckLoaded(0xc001542000)
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/snapshot/engine.go:387 +0x22d
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/processor.(*App).Info(0xc000ec9080, {{0x76?, 0x2c?}, 0xa0?, 0x0?})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/processor/abci.go:534 +0x1e2
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/blockchain/abci.(*App).Info(0xe?, {{0x32ca710?, 0x1f?}, 0xc00161e7e8?, 0x40dd7f?})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/blockchain/abci/abci.go:27 +0x6b
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/cmd/vega/node.(*appW).Info(0xc000f0d0c8?, {{0x32ca710?, 0xc00115c820?}, 0x5708ea0?, 0xc00161e878?})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/cmd/vega/node/app_wrapper.go:33 +0x59
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: github.com/tendermint/tendermint/abci/client.(*localClient).InfoSync(0xc00002daa0, {{0x32ca710?, 0xc00161e930?}, 0x4e3405?, 0x1?})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:224 +0x107
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: github.com/tendermint/tendermint/proxy.(*appConnQuery).InfoSync(0x4e6c66?, {{0x32ca710?, 0xc00161e9f0?}, 0x4e6ba4?, 0xc00019e060?})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:155 +0x29
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0016feda8, {0x3c51d00, 0xc00037c680})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/consensus/replay.go:244 +0x76
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x1}, {0xc00038ee40, 0x7}}, {0xc001e07740, 0x20}, 0x1, 0x54579, ...}, ...)
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/node/node.go:329 +0x1b8
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: github.com/tendermint/tendermint/node.NewNode(0xc001624280, {0x3c22620, 0xc000e22960}, 0xc00146b710, {0x3c07800, 0xc000f01a70}, 0x1?, 0x3c29c40?, 0xc00146b860, {0x3c28270, ...},>
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/go/pkg/mod/github.com/tendermint/tendermint@v0.34.24/node/node.go:777 +0x597
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/core/blockchain/abci.NewTmNode({{0x0}, 0x1, 0x1, 0x0, 0x0, {0xc001c59f30, 0xa}, {{0x0}, {0xc00047f800, 0x15}}, ...}, ...)
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/core/blockchain/abci/tm_node.go:78 +0x6a5
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/cmd/vega/node.(*Command).startABCI(0xc0013d3800, {0x3c4bc80, 0xc001b7d6e0}, {0x7fff40f89e9a, 0x1a}, {0x0?, 0x0?}, {0x0?, 0xc0003a77f8?})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/cmd/vega/node/node.go:410 +0x1a7
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/cmd/vega/node.(*Command).startBlockchain(0xc0013d3800, {0x7fff40f89e9a?, 0x406799?}, {0x0, 0x0}, {0x0, 0x0})
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/cmd/vega/node/node.go:297 +0x39a
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: code.vegaprotocol.io/vega/cmd/vega/node.(*Command).Run.func1()
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/cmd/vega/node/node.go:140 +0x7e
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]: created by code.vegaprotocol.io/vega/cmd/vega/node.(*Command).Run
Jan 09 20:15:51 n01.mainnet-mirror.vega.xyz visor[72759]:         /home/runner/work/vega/vega/cmd/vega/node/node.go:131 +0x685
```

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by daniel1302** [comment]
Steps to reproduce

# n01.mainnet-mirror.vega.xyz - vegavisor

## Node Info

- There is a linux user: `vega`
- User Home directory: `/home/vega`
- Vega Home: `/home/vega/vega_home`
- Tendermint Home: `/home/vega/tendermint_home`
- Vegavisor Home: `/home/vega/vegavisor_home`
- We keep binaries in the `/home/vega/vegavisor_home/current`

1. SSH into the box
2. Install required software: `sudo apt-get install -y unzip curl`
3. Switched to vega: `sudo su vega`
4. Created a run directory(required because we set it in vega config): `mkdir -p /home/vega/run`
5. Downloaded binaries from [the release page for v0.66.1](https://github.com/vegaprotocol/vega/releases/tag/v0.66.1)

```bash
cd /home/vega/bin/current
curl https://github.com/vegaprotocol/vega/releases/download/v0.66.1/vega-linux-amd64.zip
curl https://github.com/vegaprotocol/vega/releases/download/v0.66.1/visor-linux-amd64.zip
unzip vega-linux-amd64.zip
unzip visor-linux-amd64.zip
rm vega-linux-amd64.zip
rm visor-linux-amd64.zip
```

6. Backup old genesis: `cp /home/vega/tendermint_home/config/genesis.json /home/vega/tendermint_home/config/genesis.json.backup-09-01-2023`
7. Create the temporary dir: `mkdir -p /home/vega/tmp`
8. Download genesis: `curl  --output /home/vega/tendermint_home/config/genesis.json https://raw.githubusercontent.com/vegaprotocol/networks-internal/main/mainnet-mirror/genesis.json --output /home/vega/tendermint_home/config/genesis.json https://raw.githubusercontent.com/vegaprotocol/networks-internal/main/mainnet-mirror/genesis.json`
9. Make sure genesis exists: `ls -als /home/vega/tendermint_home/config/genesis.json`
10. Selected checkpoint `20230109184921-342808-d2d1f88bd051bf31a5beb7a8eab5ffc3a5faa1f5a5d8d59b44280863f0ee8b7b.cp`
11. Copied checkpoint to the temporary dir: `cp /home/vega/vega_home/state/node/checkpoints/20230109184921-342808-d2d1f88bd051bf31a5beb7a8eab5ffc3a5faa1f5a5d8d59b44280863f0ee8b7b.cp /home/vega/tmp/`
12. Loaded checkpoint into genesis: `/home/vega/bin/vega genesis load_checkpoint --tm-home /home/vega/tendermint_home/ --checkpoint-path /home/vega/tmp/20230109184921-342808-d2d1f88bd051bf31a5beb7a8eab5ffc3a5faa1f5a5d8d59b44280863f0ee8b7b.cp`
13. Uploaded genesis into the github with PR: https://github.com/vegaprotocol/networks-internal/pull/227/files
14. Init the vegavisor: `/home/vega/bin/visor init --home=/home/vega/vegavisor_home`

```bash
/home/vega/bin/visor init --home=/home/vega/vegavisor_home
2023-01-09T17:29:39.303Z        INFO    root    visor/init.go:42        Initiating genesis folder
2023-01-09T17:29:39.303Z        INFO    root    visor/init.go:47        Initiating vX.X.X upgrade folder
2023-01-09T17:29:39.304Z        INFO    root    visor/init.go:52        Saving default config file
```

15. Make sure you have the `config.toml` file in the `/home/vega/vegavisor_home/`:

```bash
cat /home/vega/vegavisor_home/config.toml

maxNumberOfFirstConnectionRetries = 10
maxNumberOfRestarts = 3
restartsDelaySeconds = 5
stopSignalTimeoutSeconds = 15

[upgradeFolders]
  "vX.X.X" = "vX.X.X"

[autoInstall]
  enabled = true
  repositoryOwner = "vegaprotocol"
  repository = "vega"
  [autoInstall.assets]
    vega = "vega-linux-amd64"
```

16. Update `maxNumberOfFirstConnectionRetries` to some bigger number: `maxNumberOfFirstConnectionRetries = 100`

17. Update the `run config` for the vegavisor in the `/home/vega/vegavisor_home/genesis/run-config.toml`. New content is:

```toml
name = "genesis"

[vega]
  [vega.binary]
    path = "/home/vega/vegavisor_home/vega"
    args = [
      "start",
      "--home", "/home/vega/vega_home",
      "--tendermint-home", "/home/vega/tendermint_home",
      "--nodewallet-passphrase-file", "/home/vega/vega_home/all-wallet-passphrase.txt",
    ]
  [vega.rpc]
    socketPath = "/home/vega/run/vega.sock"
    httpPath = "/rpc"
```

18. Update the `vega config` in the `/home/vega/vega_home/config/node/config.toml`

```diff
  NodeMode = "validator"
  UlimitNOFile = 8192
+ MaxMemoryPercent = 100
```

```diff
  [Blockchain]
    Level = "Info"
    LogTimeDebug = true
    LogOrderSubmitDebug = true
    LogOrderAmendDebug = false
    LogOrderCancelDebug = false
    ChainProvider = "tendermint"
    [Blockchain.Tendermint]
      Level = "Info"
+     RPCAddr = "tcp://127.0.0.1:26657"
-     RPCAddr = "tcp://127.0.0.1:26657"
-     LogTimeDebug = true
-     ClientAddr = "tcp://127.0.0.1:26657"
-     ClientEndpoint = "/websocket"
-     ServerPort = 26658
-     ServerAddr = "localhost"
```

```diff
    [Blockchain.Null]
      Level = "Info"
      BlockDuration = "1s"
      TransactionsPerBlock = 10
      GenesisFile = ""
      IP = "localhost"
      Port = 3101
+     [Blockchain.Null.Replay]
+       Record = false
+       Replay = false
+       ReplayFile = ""
```

```diff
+ [Ethereum]
+   Level = "Info"
+   RPCEndpoint = "https://sepolia.infura.io/v3/b4b80b9a3c4940a3a427f727230877e7"
+   RetryDelay = "15s"

  [NodeWallet]
    Level = "Info"
-   [NodeWallet.ETH]
-     Level = "Info"
-     Address = "https://sepolia.infura.io/v3/b4b80b9a3c4940a3a427f727230877e7"
-     ClefAddress = ""
```

```diff
    [EvtForward.Ethereum]
      Level = "Info"
+     PollEventRetryDuration = "20s"
```

```diff
  [Snapshot]
    Level = "Info"
    KeepRecent = 10
    RetryLimit = 5
    Storage = "GOLevelDB"
    DBPath = ""
-   StartHeight = 0
+   StartHeight = -1
```

```diff
+ [ProtocolUpgrade]
+   Level = "Info"
```

19. Update the tendermint config in the `/home/vega/tendermint_home/config/config.toml`

```diff
  # Set true to enable the peer-exchange reactor
+ pex = false
- pex = true
```

```diff
  [mempool]
  
+ # Mempool version to use:
+ #   1) "v0" - (default) FIFO mempool.
+ #   2) "v1" - prioritized mempool.
+ version = "v1"
+ 
  recheck = true
  broadcast = true
  wal_dir = ""
```

```diff
+ #######################################################
+ ###         Storage Configuration Options           ###
+ #######################################################
+ [storage]
+ 
+ # Set to true to discard ABCI responses from the state store, which can save a
+ # considerable amount of disk space. Set to false to ensure ABCI responses are
+ # persisted. ABCI responses are required for /block_results RPC queries, and to
+ # reindex events in the command-line tool.
+ discard_abci_responses = true
```

```diff
  
  # The PostgreSQL connection configuration, the connection format:
  #   postgresql://<user>:<password>@<host>:<port>/<db>?<opts>
  psql-conn = ""
+ # Comma-separated list of compositeKeys to index (by default the only key is "tx.hash")
+ # Remember that Event has the following structure: type.key
+ # type: [
+ #  key: value,
+ #  ...
+ # ]
+ #
+ # You can also index transactions by height by adding "tx.height" event here.
+ #
+ # It's recommended to index only a subset of keys due to possible memory
+ # bloat. This is, of course, depends on the indexer's DB and the volume of
+ # transactions.
+ index_keys = ""
+ 
+ # When set to true, tells indexer to index all compositeKeys (predefined keys:
+ # "tx.hash", "tx.height" and all keys from DeliverTx responses).
+ #
+ # Note this may be not desirable (see the comment above). IndexEvents has a
+ # precedence over IndexAllEvents (i.e. when given both, IndexEvents will be
+ # indexed).
+ index_all_keys = false
```

20. Copy vegavisor binary co final destination: `cp /home/vega/bin/visor /home/vega/vegavisor_home/visor`
21. Link vega binary to the final destination `ln -s /home/vega/bin/vega /home/vega/vegavisor_home/current/vega`
21. Added vegavisor service in the `/lib/systemd/system/vegavisor.service`

```conf
[Unit]
Description=vegavisor
Documentation=https://github.com/vegaprotocol/vega
After=network.target network-online.target
Requires=network-online.target

[Service]
User=vega
Group=vega
ExecStart="/home/vega/vegavisor_home/visor" run --home "/home/vega/vegavisor_home"
TimeoutStopSec=10s
LimitNOFILE=1048576
LimitNPROC=512
PrivateTmp=true
ProtectSystem=full
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```

22. Reload systemctl services: `sudo systemctl daemon-reload`
23. Stop vega: `sudo systemctl stop vega`
24. Stop tendermint `sudo systemctl stop tendermint`
25. Make sure vega is not working: `sudo systemctl status vega`
26. Make sure tendermint is not working: `sudo systemctl status tendermint`

Docs I was following:
- https://docs.google.com/document/d/1lBk3Hbdg9R5C5svbQdo5EuUln6AvvX1hh-kr9gSXFPo/edit
- https://github.com/vegaprotocol/vega/tree/develop/visor#readme
- https://github.com/vegaprotocol/vega/blob/develop/visor/visor-config.md
- For vega & tm config I was following our other network configs and config generated with `vega init` & `vega tm init`

**Comment by gordsport** [comment]
Found to be an issue in the script/process and not a core bug.
