### ISSUE TITLE
Data node panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7362]
## Issue

A data node panic has been observed on one of the mainnet observer nodes.

### Tasks (to be refined):

- identify why this issue happened
- provide a fix
- document the scenario so tests (ACs if needed) can be captured to mitigate regression in this area

### Additional information:

```
Jan 18 10:46:24 api0.mainnet.vega.xyz data-node[32133]: 2023-01-18T10:46:24.435Z        WARN        broker/sqlstore_broker.go:105        slow time update detected, time between checks 2s, block height: 8538090, total block processing t>
Jan 18 10:47:33 api0.mainnet.vega.xyz data-node[32133]: 2023-01-18T10:47:33.495Z        WARN        broker/sqlstore_broker.go:105        slow time update detected, time between checks 2s, block height: 8538135, total block processing t>
Jan 18 10:47:35 api0.mainnet.vega.xyz data-node[32133]: 2023-01-18T10:47:35.046Z        ERROR        gateway.gql        graphql/resolvers.go:2752        stream closed        {"error": "rpc error: code = Canceled desc = context canceled>
Jan 18 10:49:11 api0.mainnet.vega.xyz data-node[32133]: 2023-01-18T10:49:11.946Z        WARN        broker/sqlstore_broker.go:105        slow time update detected, time between checks 2s, block height: 8538199, total block processing t>
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd40282]
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: goroutine 171331816 [running]:
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: code.vegaprotocol.io/data-node/entities.Party.Cursor({{{0x1784202?, 0x146e5e0?}}, 0x0?})
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/workspace/data-node_v0.53.1/entities/party.go:42 +0x22
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: code.vegaprotocol.io/data-node/entities.PageEntities[...]({0xc00288c000, 0x311, 0x340}, {{0x0, 0x0}, 0x0, 0x0, 0x0})
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/workspace/data-node_v0.53.1/entities/entities.go:99 +0x6f0
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: code.vegaprotocol.io/data-node/sqlstore.(*Parties).GetAllPaged(0xc00038a130, {0x1b000c0, 0xc000baaa50}, {0x0?, 0xc00038710a?}, {{0x0, 0x0}, 0x0, 0x0, 0x0})
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/workspace/data-node_v0.53.1/sqlstore/parties.go:128 +0x69d
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: code.vegaprotocol.io/data-node/api.(*tradingDataServiceV2).GetParties(0xc000aa0000, {0x1b000c0, 0xc000baaa50}, 0xc000d46740)
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/workspace/data-node_v0.53.1/api/trading_data_v2.go:790 +0x113
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: code.vegaprotocol.io/protos/data-node/api/v2._TradingDataService_GetParties_Handler.func1({0x1b000c0, 0xc000baaa50}, {0x1638040?, 0xc000d46740})
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/GOPATH/pkg/mod/code.vegaprotocol.io/protos@v0.53.0/data-node/api/v2/trading_data_grpc.pb.go:1292 +0x7b
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: code.vegaprotocol.io/data-node/api.remoteAddrInterceptor.func1({0x1b000c0, 0xc000baa9f0}, {0x1638040, 0xc000d46740}, 0xc004886440, 0xc004ed6708)
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/workspace/data-node_v0.53.1/api/server.go:244 +0x637
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: code.vegaprotocol.io/protos/data-node/api/v2._TradingDataService_GetParties_Handler({0x175dc20?, 0xc000aa0000}, {0x1b000c0, 0xc000baa9f0}, 0xc00285de00, 0xc000378090)
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/GOPATH/pkg/mod/code.vegaprotocol.io/protos@v0.53.0/data-node/api/v2/trading_data_grpc.pb.go:1294 +0x138
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00075a000, {0x1b07440, 0xc001418ea0}, 0xc003d1a7e0, 0xc0005ac390, 0x26f8170, 0x0)
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/GOPATH/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: google.golang.org/grpc.(*Server).handleStream(0xc00075a000, {0x1b07440, 0xc001418ea0}, 0xc003d1a7e0, 0x0)
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/GOPATH/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/GOPATH/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:921 +0x98
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Jan 18 10:49:28 api0.mainnet.vega.xyz data-node[32133]:         /jenkins/GOPATH/pkg/mod/google.golang.org/grpc@v1.45.0/server.go:919 +0x28a
Jan 18 10:49:28 api0.mainnet.vega.xyz systemd[1]: datanode.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 18 10:49:28 api0.mainnet.vega.xyz systemd[1]: datanode.service: Failed with result 'exit-code'.
```

**Comment by pscott31** [comment]
OK so this happens because of a bug in datanode 0.53. We construct the cursor for a party using its VegaTime like this:

```go
func (p Party) Cursor() *Cursor {
	return NewCursor(p.VegaTime.In(time.UTC).Format(time.RFC3339Nano))
}
```

Unfortunately the _network_ party is special and has a NULL vegatime which makes this blow up. It is trivial to recreate just by running the following graphql query:

```gql
{partiesConnection{edges{cursor, node{id}}}}
```

In recent datanodes we changed how cursors are generated and this is no longer an issue (double checked). No action required, except maybe to ask people politely not to use partiesConnection until we've upgraded the mainnet datanode version.
