### ISSUE TITLE
panic on lite node (RetentionPeriod = "1 day"): context cancelled whilst waiting for create snapshot lock

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#7691]
This issue has happened [again](https://github.com/vegaprotocol/vega/issues/7691#issuecomment-1465023507).
It happened on `lite` node again `RetentionPeriod = "1 day"`.
More context: https://vegaprotocol.slack.com/archives/C02KVKMAE82/p1677501066611329
And also here: https://vegaprotocol.slack.com/archives/CE5L3T60J/p1678568973622639?thread_ts=1678449879.304609&cid=CE5L3T60J

# Problem encountered
Panic on `n07.stagnet1.vega.xyz` running `v0.68.0`.

# Observed behaviour
The server stopped due to the panic

# Expected behaviour
There should not be a panic

# Evidence

## Logs
```log
Feb 25 15:18:12 n07.stagnet1.vega.xyz visor[855783]: 2023-02-25T15:18:12.786Z        INFO        tendermint        consensus/state.go:1602        finalizing commit of block        {"hash": "309A6EAD1C41D80FC85811D20C74ADAB921403D3CA0A27FB3D3A8DD5803665D5", "root": "72F0B011EE7B798D01C600DF8DAB6E716E523755E01EFB5750BD44D8C2D8E2CB", "num_txs": 198}
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: panic: context cancelled whilst waiting for create snapshot lock
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: goroutine 956 [running]:
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).createNewSnapshot(0xc000e3ca00, {0x3b677f0?, 0xc003a7e680}, {0xc000149640, 0x1a}, 0x1330b35c53ad1?, 0x1)
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/work/vega/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:69 +0x1309
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).CreateSnapshotAsynchronously(...)
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/work/vega/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:44
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).SnapshotData(0x0?, {0x3b677f0?, 0xc003a7e680?}, {0xc000149640?, 0x20?}, 0x0?)
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/work/vega/vega/datanode/networkhistory/snapshot/service.go:64 +0x85
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855783]: 2023-02-25T15:18:13.074Z        INFO        tendermint        state/execution.go:333        executed block        {"height": 464398, "num_valid_txs": 198, "num_invalid_txs": 0}
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: code.vegaprotocol.io/vega/datanode/networkhistory.(*BlockCommitHandler).OnBlockCommitted.func1()
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/work/vega/vega/datanode/networkhistory/block_commit_handler.go:50 +0x43
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: github.com/cenkalti/backoff.RetryNotify(0xc03f165dc8, {0x3b50428, 0xc0362c0a20}, 0x0)
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37 +0x1ac
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: github.com/cenkalti/backoff.Retry(...)
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: code.vegaprotocol.io/vega/datanode/networkhistory.(*BlockCommitHandler).OnBlockCommitted(0xc00245a340, {0x3b677f0?, 0xc003a7e680?}, {0xc000149640?, 0xc04db91d38?}, 0xc0015860c0?, 0x0?)
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/work/vega/vega/datanode/networkhistory/block_commit_handler.go:61 +0x1af
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).Receive(0xc001394a00, {0x3b677f0, 0xc003a7e680})
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:134 +0x1a3
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func6()
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/work/vega/vega/cmd/data-node/commands/start/node.go:144 +0x34
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: golang.org/x/sync/errgroup.(*Group).Go.func1()
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]: created by golang.org/x/sync/errgroup.(*Group).Go
Feb 25 15:18:13 n07.stagnet1.vega.xyz visor[855784]:         /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by pscott31** [comment]
I don't think this is a bug per se, though it is clearly an issue - I think this is just because snapshotting is getting progressively slower till it got to the point were a previous snapshot was going on at the time it is trying to make a new one:

![image](https://user-images.githubusercontent.com/94362991/221564029-a4a3e60b-935f-4408-ae95-dfc1c5cd7121.png)

I know @guoguojin has been doing some work on this, but I'm not sure it's made it into stagnet1 yet I'll ask

**Comment by guoguojin** [comment]
No, I was working on the snapshot loading problem. I can take a look at this now though.

**Comment by ettec** [comment]
Look at the context, the whole box is running  like a dog, this is symptom not cause,:

https://metrics.vega.xyz/d/datanode-stagnet1/data-node?orgId=1&from=now-7d&to=now&var-instance=n07.stagnet1.vega.xyz

**Comment by fkondej** [comment]
We hit this issue again on the same machine `n07.stagnet1.vega.xyz`.

Context: https://vegaprotocol.slack.com/archives/C02KVKMAE82/p1677501066611329

It is a `lite` node with `RetentionPeriod = "1 day"` set in config.
NOTE: This is our only `lite` node across all networks. Since this problem has happened twice on that machine, this means this is a quite common issue.

```
2023-03-11T11:37:09.758Z        INFO        tendermint        txindex/indexer_service.go:97        indexed block exents        {"height": 76899}
2023-03-11T11:37:09.982Z        INFO        datanode.networkHistory.snapshot        snapshot/service_create_snapshot.go:117        compressing current state snapshot data
panic: context cancelled whilst waiting for create snapshot lock
goroutine 1046 [running]:
code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).createNewSnapshot(0xc001ffe5a0, {0x53c1ff8?, 0xc005674480}, {0xc0001bdd60, 0x1a}, 0x384e8cf03937?, 0x1)
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:69 +0x1309
code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).CreateSnapshotAsynchronously(...)
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:44
code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).SnapshotData(0x0?, {0x53c1ff8?, 0xc005674480?}, {0xc0001bdd60?, 0x20?}, 0x0?)
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/networkhistory/snapshot/service.go:64 +0x85
code.vegaprotocol.io/vega/datanode/networkhistory.(*BlockCommitHandler).OnBlockCommitted.func1()
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/networkhistory/block_commit_handler.go:50 +0x43
github.com/cenkalti/backoff.RetryNotify(0xc003865d98, {0x53aa288, 0xc03025e8e0}, 0x0)
        /jenkins/GOPATH/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37 +0x1ac
github.com/cenkalti/backoff.Retry(...)
        /jenkins/GOPATH/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:24
code.vegaprotocol.io/vega/datanode/networkhistory.(*BlockCommitHandler).OnBlockCommitted(0xc004a6a000, {0x53c1ff8?, 0xc005674480?}, {0xc0001bdd60?, 0xc02e4d1d08?}, 0xc004c40000?, 0x0?)
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/networkhistory/block_commit_handler.go:61 +0x1af
code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).Receive(0xc005f2ea00, {0x53c1ff8, 0xc005674480})
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/datanode/broker/sqlstore_broker.go:134 +0x1a3
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func6()
        /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/data-node/commands/start/node.go:150 +0x75
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /jenkins/GOPATH/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /jenkins/GOPATH/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```

**Comment by gordsport** [comment]
Moving to a later sprint, not been able to recreate

**Comment by gordsport** [comment]
Closing - to be reopened should this arise again
