### ISSUE TITLE
Data-node panics when event buffer is disabled

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7769]
# Problem encountered
When We disabled event buffer source, and we got panic after restarting:

```toml
  UseBufferedEventSource = false
```

```
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: 2023-03-06T09:58:09.003Z        INFO        datanode.api.grpc        api/server.go:336        Starting gRPC based API        {"addr": "0.0.0.0", "port": "3007"}
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x252af75]
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: goroutine 774 [running]:
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: code.vegaprotocol.io/vega/datanode/broker.(*fanOutEventSource).Listen(0xc0001790a0)
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]:         /home/runner/work/vega/vega/datanode/broker/fan_out_event_source.go:50 +0x95
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).Receive(0xc004f7ac80, {0x3b69770, 0xc004f71780})
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]:         /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:113 +0x44
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func6()
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]:         /home/runner/work/vega/vega/cmd/data-node/commands/start/node.go:144 +0x34
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: golang.org/x/sync/errgroup.(*Group).Go.func1()
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]:         /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]: created by golang.org/x/sync/errgroup.(*Group).Go
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537658]:         /home/runner/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
Mar 06 09:58:09 n06.testnet.vega.xyz visor[537648]: 2023-03-06T09:58:09.018Z        DEBUG        visor        visor/binaries_runner.go:103        Killing binary        {"binaryPath": "/home/vega/vegavisor_home/curre
```

# Observed behaviour
The application panicked 

# Expected behaviour
Application should start

# System response
See log above

# Steps to reproduce

## Manual
1. Stop the running node
2. Disable the event buffer
3. Start the node without unsafe reset all

## Automation
Link to automation and explanation on how to run it to reproduce the problem/bug

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by guoguojin** [comment]
This looks like it has already been fixed by @pscott31 in this commit https://github.com/vegaprotocol/vega/commit/b414ac92cd33437cfc8b356012f52b8939acf24a. @daniel1302 , can you check and confirm if this is still an issue?
