### ISSUE TITLE
Stagnet3 panic after protocol upgrade

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7898]
## Issue

After todays protocol upgrade on stagnet3 the following panic on stagnet3 was logged:

```
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: panic: Non-zero buy sum-product with no buy orders [recovered]
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         panic: Non-zero buy sum-product with no buy orders
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: goroutine 181 [running]:
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/cmd/vega/node.(*Command).Run.func1.1()
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/cmd/vega/node/node.go:137 +0x59
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: panic({0x4393e60, 0xc0019be1e0})
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /usr/local/go/src/runtime/panic.go:884 +0x212
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x0?, {0x0?, 0x0?, 0xc011d686c0?})
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc001cc8340, {0x0, 0x0, 0x0})
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: go.uber.org/zap.(*Logger).Panic(0x187d452?, {0x4d0af2c?, 0x73afb163cacd4000?}, {0x0, 0x0, 0x0})
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/positions.(*MarketPosition).UpdateOnOrderChange(0xc011da5300, 0xc00f0b02a0, 0x13814180?, 0xc01380d820, 0x18db, 0x0)
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/positions/market_position.go:90 +0x488
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/positions.(*MarketPosition).UnregisterOrder(...)
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/positions/market_position.go:67
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/positions.(*Engine).UnregisterOrder(0xc000ed0af0, {0x53d9560, 0xc011ead950}, 0xc013811ee0)
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/positions/engine.go:195 +0x23a
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/positions.(*SnapshotEngine).UnregisterOrder(...)
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/positions/snapshot.go:56
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/execution.(*Market).removeLPOrdersFromBook(0xc012b778c0, {0x53d9560, 0xc011ead950}, {0xc012073080, 0x8, 0x0?})
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/special_orders.go:464 +0x8b
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/execution.(*Market).repriceAllSpecialOrders(0xc012b778c0, {0x53d9560, 0xc011ead950}, 0x0?, {0xc0115f30f8?, 0x0?, 0x0?}, 0x0?, 0x0?)
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/special_orders.go:157 +0x37c
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/execution.(*Market).checkForReferenceMoves(0xc012b778c0, {0x53d9560, 0xc011ead950}, {0xc0115f30f8, 0x1, 0x1}, 0x0)
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/reference_price_moves.go:80 +0x33c
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/execution.(*Market).removeExpiredOrders(0xc012b778c0, {0x53d9560, 0xc011ead950}, 0xc00f007fc0?)
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/market.go:3093 +0x765
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/execution.(*Market).OnTick(0xc012b778c0, {0x53d9560, 0xc011ead950}, {0x4c?, 0xc0120dc240?, 0x0?})
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/market.go:697 +0x378
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0xc000279dc0, {0x53d9560, 0xc011ead950}, {0x1?, 0x53f3a38?, 0x0?})
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]:         /jenkins/workspace/private/Deployments/Publish-vega-dev-releases/vega/core/execution/engine.go:778 +0x253
Mar 21 02:12:35 n00.stagnet3.vega.xyz visor[645265]: code.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
```

### Additional information

- https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1679386055547379

**Comment by witgaw** [comment]
The issue here was that https://github.com/vegaprotocol/vega/issues/7880 introduced a change that was "breaking" in a sense of updating a network with protocol upgrade functionality. A network started from scratch works fine.
