### ISSUE TITLE
Datanode panic / failed to snapshot data after network closeout of party / orders copy failure / failed to open orders_live

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#7911]
Party distressed and closedout
Numerous closeout orders and network trades produced

datanode panics

2023-03-21T16:41:07.052Z	INFO	provider.simple	simple/provider.go:115	announce - end - QmXLcfu9b6UCkRH89KkG4ZkHfc7mpZpxsoUTpFdXKCEqho
panic: failed to snapshot data

goroutine 114728 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc008402200?})
	/Users/paulwebb/Projects/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0023428f0, {0xc0083af1c0, 0x1, 0x1})
	/Users/paulwebb/Projects/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc001266a90?, {0x408ea7d?, 0x462?}, {0xc0083af1c0, 0x1, 0x1})
	/Users/paulwebb/Projects/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).createNewSnapshot.func4()
	/Users/paulwebb/repos/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:119 +0x2da
created by code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).createNewSnapshot
	/Users/paulwebb/repos/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:124 +0x9ca

```2023-03-21T16:41:07.013Z	INFO	datanode.networkHistory.service.store	networkhistory/service.go:334	removed 0 old history segments
2023-03-21T16:41:20.630Z	INFO	datanode.networkHistory.snapshot	snapshot/service_create_snapshot.go:44	creating snapshot for {History Snapshot for Chain ID:testnet-001 Height From:1101 Height To:1122}
2023-03-21T16:41:20.667Z	INFO	datanode.networkHistory.snapshot	snapshot/service_create_snapshot.go:117	copying all table data....
2023-03-21T16:41:20.995Z	PANIC	datanode.networkHistory.snapshot	snapshot/service_create_snapshot.go:119	failed to snapshot data	{"error": "failed to copy table data:failed to execute copy: failed to execute copy sql copy (select * from orders_live order by id) to '/Users/paulwebb/repos/networkdata/testnet/data-node/node2/state/data-node/networkhistory/snapshotscopyto/testnet-001-1122-currentstatesnapshot/orders_live': ERROR: could not open file \"/Users/paulwebb/repos/networkdata/testnet/data-node/node2/state/data-node/networkhistory/snapshotscopyto/testnet-001-1122-currentstatesnapshot/orders_live\" for writing: No such file or directory (SQLSTATE 58P01)"}

**Comment by guoguojin** [comment]
This looks like an issue that commonly happens when using the Docker version of Postgres. The path to export to is not available in the Docker container so when the copy command is executed by Postgres, it can't find the output path and returns an error.

In the vega repo, under the scripts folder, the postgres-docker.sh script checks for $VEGA_HOME and mounts it to the docker volume when Postgres starts so that the snapshot path is available to the Postgres container. I think Nomad would need to do something similar when it spins up the network, otherwise it would not be possible for us to create that path inside the Postgres container for the copy command to work.
