### ISSUE TITLE
Panic for protocol upgrade

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#8133]
# Problem encountered
We got this panic on validators-testnet

Visor config:

```toml
# Try every 2 seconds, 43200 retries is 24h
maxNumberOfFirstConnectionRetries = 43200
maxNumberOfRestarts = 3
restartsDelaySeconds = 5
stopSignalTimeoutSeconds = 15

[upgradeFolders]
  "vX.X.X" = "vX.X.X"

[autoInstall]
  enabled = true
  repositoryOwner = "vegaprotocol"
  repository = "vega"
  [autoInstall.assets]
    [autoInstall.assets.vega]
      asset_name = "vega-linux-amd64.zip"
      binary_name = "vega"
```

```
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: 2023-04-13T13:00:08.665Z        DEBUG        visor        visor/visor_folders.go:96        preparing next upgrade folder        {"vegaTagVersion": "v0.70.3"}
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xc31466]
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: goroutine 1 [running]:
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: code.vegaprotocol.io/vega/visor.(*Visor).installUpgradeFolder(0xc00007f320, {0x10e8c98, 0xc000120980}, {0xc000130150, 0x21}, {0xc0001d04a0, 0x7}, {0x1, {0xc0000434a0, 0xc}, ...})
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/work/vega/vega/visor/visor_folders.go:80 +0x306
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: code.vegaprotocol.io/vega/visor.(*Visor).prepareNextUpgradeFolder(0xc00007f320, {0x10e8c98, 0xc000120980}, {0xc0001d04a0, 0x7})
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/work/vega/vega/visor/visor_folders.go:112 +0x307
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: code.vegaprotocol.io/vega/visor.(*Visor).Run(0xc00007f320, {0x10e8cd0, 0xc0000420d8})
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/work/vega/vega/visor/visor.go:188 +0x549
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: main.glob..func2(0x179a760, {0xea252a?, 0x2?, 0x2?})
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/work/vega/vega/cmd/visor/run.go:50 +0x125
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: github.com/spf13/cobra.(*Command).execute(0x179a760, {0xc00007e320, 0x2, 0x2})
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: github.com/spf13/cobra.(*Command).ExecuteC(0x179a480)
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: github.com/spf13/cobra.(*Command).Execute(...)
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]: main.main()
Apr 13 13:00:08 n00.validators-testnet.vega.xyz visor[1658062]:         /home/runner/work/vega/vega/cmd/visor/main.go:28 +0x54
Apr 13 13:00:08 n00.validators-testnet.vega.xyz systemd[1]: vegavisor.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 13 13:00:08 n00.validators-testnet.vega.xyz systemd[1]: vegavisor.service: Failed with result 'exit-code'.
```

# Evidence

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by wwestgarth** [comment]
Possibly already fixed?
https://github.com/vegaprotocol/vega/issues/7974

**Comment by karlem** [comment]
@daniel1302 is it the latest Visor that runs there? It seems like it is not the latest Visor version?

**Comment by fkondej** [comment]
We are using the `v0.70.2` version on `Validator's Testnet`, and we got the panic from this ticket on every `data-node` node.

I thought this panic was the same as in https://github.com/vegaprotocol/vega/issues/7974, but if that is a different one than sorry for the confusion.

**Comment by fkondej** [comment]
@karlem I have created a separate ticket for the missing config: https://github.com/vegaprotocol/vega/issues/8135

**Comment by gordsport** [comment]
Closing as this has been resolved in a later version.
