### ISSUE TITLE
Consensus error observed with 0.71.6 

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#8552]
A validator has been running version 0.71.6 and after a few hours has had a consensus error, it affected only the validator node, not the data-node.

```
2023-06-20T14:26:38.080Z        ERROR   tendermint      consensus/state.go:1280 prevote step: ProposalBlock is invalid  {"err": "wrong Block.Header.LastResultsHash.  Expected 38CB38B5C322AD07534E8CE02B692E67FDE5A98136F2D6984D4BAD952BD44F87, got 8E22A42006AF871B3FD472E39C6299546318316E798AB6EF27BD036820AB0186"}
2023-06-20T14:26:38.276Z        ERROR   tendermint      consensus/state.go:732  CONSENSUS FAILURE!!!    {"err": "precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.LastResultsHash.  Expected 38CB38B5C322AD07534E8CE02B692E67FDE5A98136F2D6984D4BAD952BD44F87, got 8E22A42006AF871B3FD472E39C6299546318316E798AB6EF27BD036820AB0186", "stack": "goroutine 429 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c\npanic({0x2d3b940, 0xc00c72fab0})\n\t/usr/local/go/src/runtime/panic.go:884 +0x212\ngithub.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc00a703c00, 0x3bfa30, 0x0)\n\t/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1414 +0x1739\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc00a703c00, 0xc00579cdc0, {0xc006987b30, 0x28})\n\t/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2137 +0x13d8\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc00a703c00, 0xc00579cdc0, {0xc006987b30?, 0xc0054ef900?})\n\t/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc00a703c00, {{0x3ca1f60?, 0xc009b153b0?}, {0xc006987b30?, 0x0?}})\n\t/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x170\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc00a703c00, 0x0)\n\t/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x3f9\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0x12d\n"}
```
The logs from the validator can be seen:
- [validator.log](https://github.com/vegaprotocol/vega/files/11801838/validator.log)

**Comment by gordsport** [comment]
Closing as wont fix:

There was a pre-release version v0.71.6 created 3 weeks ago, It was removed it today in order to get the security advisory patch in for the protocol upgrade.

The validator has pulled the version from 3 weeks ago and it did not have the latest changes included.

Team actions to take away:
- review how we number versions to avoid this in the future
- document the security patch process (WIP) so it avoids this in the future
