### ISSUE TITLE
[Bug]: Panic on creating a new spot market

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#8626]
### Problem encountered

Panic on creating a new spot market

### Observed behaviour

Panic on creating a new spot market

### Expected behaviour

should be able to create a new spot market

### Steps to reproduce

```bash
Run the below system test:

System Test Branch - feat-spot-execution-tests
System Test Name - test_spot_market
Vega Branch - spot-execution
```

### Software version

Vega Branch - spot-execution

### Failing test

test_spot_market

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/78929/

### Relevant log output

```shell
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/78929/artifact/testnet/logs/testnet-nodeset-validators-1-validator/vega-validator-1.stderr-2023-06-28T15%3A08%3A16Z.log



panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21cda6b]

goroutine 24938 [running]:
code.vegaprotocol.io/vega/core/types.ExecSpotMarket.IntoProto({0xc004110370, 0xc00432a100, 0xc00baf1c40, 0xc005631398, {0x7852110, 0x0, 0x0}, 0xc00ab12860, 0xc00ab12880, 0xc00ab128a0, ...})
	/jenkins/workspace/common/system-tests-wrapper/vega/core/types/snapshot_nodes.go:3191 +0x38b
code.vegaprotocol.io/vega/core/types.ExecutionMarkets.IntoProto({{0x0, 0x0, 0x0}, {0xc000014820, 0x1, 0x1}, {0x7852110, 0x0, 0x0}})
	/jenkins/workspace/common/system-tests-wrapper/vega/core/types/snapshot_nodes.go:3329 +0x2f8
code.vegaprotocol.io/vega/core/types.PayloadExecutionMarkets.IntoProto(...)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/types/snapshot_nodes.go:2055
code.vegaprotocol.io/vega/core/types.(*PayloadExecutionMarkets).plToProto(0x48?)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/types/snapshot_nodes.go:2062 +0x95
code.vegaprotocol.io/vega/core/types.Payload.IntoProto({{0x56e7420, 0xc000014858}, {0x0, 0x0, 0x0}, {0x0, 0x0}})
	/jenkins/workspace/common/system-tests-wrapper/vega/core/types/snapshot_nodes.go:887 +0x68
code.vegaprotocol.io/vega/core/execution.(*Engine).serialise(0xc000428280)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/engine_snapshot.go:197 +0x3c9
code.vegaprotocol.io/vega/core/execution.(*Engine).GetState(0x47af140?, {0xc0014a86c0?, 0xc0035d7b90?})
	/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/engine_snapshot.go:219 +0x19
code.vegaprotocol.io/vega/core/snapshot.worker(0xc001492000, 0xc0039edfd0?, 0x23246ce?, 0x572b810?, 0xc005347b80)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:997 +0x335
created by code.vegaprotocol.io/vega/core/snapshot.(*Engine).snapshotNow
	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:761 +0x1dd
```

**Comment by Sohill-Patel** [comment]
issue fixed in spot-execution branch of vega
