### ISSUE TITLE
[Bug]: Error when submitting stop order

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#8651]
### Problem encountered

Unable to successfully submit a stop order

### Observed behaviour

Receive `requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))` when submitting a stop order

### Expected behaviour

Should be able to submit stop orders.

### Steps to reproduce

```bash
Run the below test:

System Test name - test_stop_order_submit
System Test Branch - feat_stop_orders_1

Jenkins Result - https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/79475/testReport/
```

### Software version

Vega core - develop

### Failing test

test_stop_order_submit

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/79475/

### Configuration used

```shell
Stop Order Submission:

{'stopOrdersSubmission': {'risesAbove': {'orderSubmission': {'marketId': 'd9727e852302d44f5e48a105f206a96c2637d0cd8fae7b7efb480ed261714f26', 'price': '95000000', 'size': '10000000', 'side': 'SIDE_BUY', 'timeInForce': 'TIME_IN_FORCE_IOC', 'type': 'TYPE_LIMIT', 'reference': 'test_stop_order_submit[order_param0]-16af3835', 'reduceOnly': True, 'expiresAt': '0', 'postOnly': False}, 'expiresAt': '0', 'expiryStrategy': 'EXPIRY_STRATEGY_SUBMIT', 'trailingPercentOffset': '0.5'}, 'fallsBelow': {'orderSubmission': {'marketId': 'd9727e852302d44f5e48a105f206a96c2637d0cd8fae7b7efb480ed261714f26', 'price': '95000000', 'size': '10000000', 'side': 'SIDE_BUY', 'timeInForce': 'TIME_IN_FORCE_IOC', 'type': 'TYPE_LIMIT', 'reference': 'test_stop_order_submit[order_param0]-16af3835', 'reduceOnly': True, 'expiresAt': '0', 'postOnly': False}, 'expiresAt': '0', 'expiryStrategy': 'EXPIRY_STRATEGY_SUBMIT', 'trailingPercentOffset': '0.5'}}}
```

### Relevant log output

```shell
Submitting stop order with ref: test_stop_order_submit[order_param0]-16af3835 {'stopOrdersSubmission': {'risesAbove': {'orderSubmission': {'marketId': 'd9727e852302d44f5e48a105f206a96c2637d0cd8fae7b7efb480ed261714f26', 'price': '95000000', 'size': '10000000', 'side': 'SIDE_BUY', 'timeInForce': 'TIME_IN_FORCE_IOC', 'type': 'TYPE_LIMIT', 'reference': 'test_stop_order_submit[order_param0]-16af3835', 'reduceOnly': True, 'expiresAt': '0', 'postOnly': False}, 'expiresAt': '0', 'expiryStrategy': 'EXPIRY_STRATEGY_SUBMIT', 'trailingPercentOffset': '0.5'}, 'fallsBelow': {'orderSubmission': {'marketId': 'd9727e852302d44f5e48a105f206a96c2637d0cd8fae7b7efb480ed261714f26', 'price': '95000000', 'size': '10000000', 'side': 'SIDE_BUY', 'timeInForce': 'TIME_IN_FORCE_IOC', 'type': 'TYPE_LIMIT', 'reference': 'test_stop_order_submit[order_param0]-16af3835', 'reduceOnly': True, 'expiresAt': '0', 'postOnly': False}, 'expiresAt': '0', 'expiryStrategy': 'EXPIRY_STRATEGY_SUBMIT', 'trailingPercentOffset': '0.5'}}}
2023-06-30 13:06:58.892:[INFO] [MainProcess] [MainThread] [   clientv2.py]:[    __init__]:[  38] instantiating WalletClientV2: http://127.0.0.1:1789, /jenkins/workspace/common/system-tests-wrapper/system-tests/vegacapsule/api-token-passphrase-file, /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/wallet
2023-06-30 13:06:58.893:[INFO] [MainProcess] [MainThread] [   clientv2.py]:[       login]:[ 174] logging in to: C65E3882D5
2023-06-30 13:06:58.897:[INFO] [MainProcess] [MainThread] [   clientv2.py]:[   signtx_v2]:[ 370] calling jsonrpc client.send_transaction for wallet: C65E3882D5, pubkey: fceb6f28e37d40b28dd19a79b00b06406ba9de471ce6190a10b31de0f20e2b91: req: {'stopOrdersSubmission': {'risesAbove': {'orderSubmission': {'marketId': 'd9727e852302d44f5e48a105f206a96c2637d0cd8fae7b7efb480ed261714f26', 'price': '95000000', 'size': '10000000', 'side': 'SIDE_BUY', 'timeInForce': 'TIME_IN_FORCE_IOC', 'type': 'TYPE_LIMIT', 'reference': 'test_stop_order_submit[order_param0]-16af3835', 'reduceOnly': True, 'expiresAt': '0', 'postOnly': False}, 'expiresAt': '0', 'expiryStrategy': 'EXPIRY_STRATEGY_SUBMIT', 'trailingPercentOffset': '0.5'}, 'fallsBelow': {'orderSubmission': {'marketId': 'd9727e852302d44f5e48a105f206a96c2637d0cd8fae7b7efb480ed261714f26', 'price': '95000000', 'size': '10000000', 'side': 'SIDE_BUY', 'timeInForce': 'TIME_IN_FORCE_IOC', 'type': 'TYPE_LIMIT', 'reference': 'test_stop_order_submit[order_param0]-16af3835', 'reduceOnly': True, 'expiresAt': '0', 'postOnly': False}, 'expiresAt': '0', 'expiryStrategy': 'EXPIRY_STRATEGY_SUBMIT', 'trailingPercentOffset': '0.5'}}, 'propagate': True, 'pubKey': 'fceb6f28e37d40b28dd19a79b00b06406ba9de471ce6190a10b31de0f20e2b91'}
2023-06-30 13:06:58.897:[INFO] [MainProcess] [MainThread] [   clientv2.py]:[     _header]:[  53] using token: K2WCrTdzy5ujYJdp2yldWjLdMIaUlwciOrpVyc69AmavBJi7ofdPSWQOcZ0nrt0e
FAILED                                                                   [100%]2023-06-30 13:06:59.370:[INFO] [MainProcess] [MainThread] [   conftest.py]:[pytest_runtest_makereport]:[  62] Marking test as failed for use in tearDown
```

**Comment by MuthuVega** [comment]
Panic in Wallet

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/79475/artifact/testnet/logs/testnet-vegawallet/wallet-1.stderr-2023-06-30T13%3A05%3A06Z.log/*view*/

2023/06/30 13:06:58 http: panic serving 127.0.0.1:56984: command &{rises_above:{order_submission:{market_id:"d9727e852302d44f5e48a105f206a96c2637d0cd8fae7b7efb480ed261714f26"  price:"95000000"  size:10000000  side:SIDE_BUY  time_in_force:TIME_IN_FORCE_IOC  type:TYPE_LIMIT  reference:"test_stop_order_submit[order_param0]-16af3835"  reduce_only:true}  expires_at:0  expiry_strategy:EXPIRY_STRATEGY_SUBMIT  trailing_percent_offset:"0.5"}  falls_below:{order_submission:{market_id:"d9727e852302d44f5e48a105f206a96c2637d0cd8fae7b7efb480ed261714f26"  price:"95000000"  size:10000000  side:SIDE_BUY  time_in_force:TIME_IN_FORCE_IOC  type:TYPE_LIMIT  reference:"test_stop_order_submit[order_param0]-16af3835"  reduce_only:true}  expires_at:0  expiry_strategy:EXPIRY_STRATEGY_SUBMIT  trailing_percent_offset:"0.5"}} is not supported
goroutine 309 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0xbf
panic({0x4650160, 0xc001d4e150})
	/usr/local/go/src/runtime/panic.go:890 +0x262
code.vegaprotocol.io/vega/wallet/commands.WrapRequestCommandIntoInputData(0xc001d46820?, 0x4e33228?)
	/jenkins/workspace/common/system-tests-wrapper/vega/wallet/commands/commands.go:191 +0xf3d
code.vegaprotocol.io/vega/wallet/commands.ToInputData(0xc0017186f0?, 0xc1)
	/jenkins/workspace/common/system-tests-wrapper/vega/wallet/commands/commands.go:88 +0x57
code.vegaprotocol.io/vega/wallet/api.(*ClientSendTransaction).Handle(0xc001579680, {0x5743d38, 0xc001d2c5d0}, {0x47f9160, 0xc001d2c630}, {{0xc0016f2de0, 0xa}, {0x56f9648, 0x0}, {0xc000439420, ...}, ...})
	/jenkins/workspace/common/system-tests-wrapper/vega/wallet/api/client_send_transaction.go:147 +0xfaf
code.vegaprotocol.io/vega/wallet/api.(*ClientAPI).SendTransaction(0xc001d24400?, {0x5743d38?, 0xc001d2c5d0?}, {0x47f9160?, 0xc001d2c630?}, {{0xc0016f2de0, 0xa}, {0x56f9648, 0x0}, {0xc000439420, ...}, ...})
	/jenkins/workspace/common/system-tests-wrapper/vega/wallet/api/api.go:221 +0x6d
code.vegaprotocol.io/vega/wallet/service/v2.NewAPI.func6({0x5743d38, 0xc001d2c5d0}, 0x20879d6?, 0x78944c0?, {{0xc001d2e1e8, 0x3}, {0xc0003a3350, 0x17}, {0x47f9160, 0xc001d2c630}, ...})
	/jenkins/workspace/common/system-tests-wrapper/vega/wallet/service/v2/api.go:137 +0x2da
code.vegaprotocol.io/vega/wallet/service/v2.(*API).processJSONRPCRequest(0xc0016b3ba0, {0x5743d38, 0xc001d2c5d0}, {0xc001d04690, 0x40}, 0x55555555555555?, 0x203000?, {{0xc001d2e1e8, 0x3}, {0xc0003a3350, ...}, ...})
	/jenkins/workspace/common/system-tests-wrapper/vega/wallet/service/v2/endpoint_handle_request.go:128 +0x7e2
code.vegaprotocol.io/vega/wallet/service/v2.(*API).HandleRequest(0xc0016b3ba0, {0x573e680, 0xc0005fb340}, 0xc001ba3a00, {0xc0016dc0f0?, 0x0?, 0xc001d0cc2b?})
	/jenkins/workspace/common/system-tests-wrapper/vega/wallet/service/v2/endpoint_handle_request.go:41 +0x577
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00153d3e0, {0x573e680, 0xc0005fb340}, 0xc001ba3a00)
	/jenkins/GOPATH/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c
github.com/rs/cors.(*Cors).Handler.func1({0x573e680, 0xc0005fb340}, 0xc001ba3a00)
	/jenkins/GOPATH/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4
net/http.HandlerFunc.ServeHTTP(0x0?, {0x573e680?, 0xc0005fb340?}, 0x2087df4?)
	/usr/local/go/src/net/http/server.go:2109 +0x2f
net/http.serverHandler.ServeHTTP({0x572f8d8?}, {0x573e680, 0xc0005fb340}, 0xc001ba3a00)
	/usr/local/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0016d9f40, {0x5743d38, 0xc001762f90})
	/usr/local/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x4db
