### ISSUE TITLE
[Bug]: Core error on settling a market

### ISSUE THREAD

**Issue by TomMcL** [vegaprotocol/vega#8698]
### Problem encountered

Whilst setting up market sim to handle successor markets in fuzzing tests, I have hit a couple of core crashing errors at point of settling a market. These could be related to each other, and don't immediately appear to have any relationship to the actual successor markets changes.

### Observed behaviour

When settling a market, the core crashes and exits.

On commit d79ae49de1cdd3d7ebc40efb38d5c6c4f82eefb3 this error was encountered:

```
panic: settlement balance is not zero

goroutine 31149 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x80?, 0x1?, {0x1?, 0x0?, 0x0?})
        /Users/tom/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x7c
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x140040349c0, {0x1400caf2580, 0x1, 0x1})
        /Users/tom/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x2bc
go.uber.org/zap.(*Logger).Panic(0x2?, {0x1030f81a6?, 0x0?}, {0x1400caf2580, 0x1, 0x1})
        /Users/tom/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x54
code.vegaprotocol.io/vega/core/collateral.(*Engine).CheckLeftOverBalance(0x140014cd050, {0x1041cff80, 0x14009b04690}, 0x1400b720be0, {0x14002328900, 0x2a, 0x40?}, {0x14003cd4cc0, 0x40})
        /Users/tom/Code/vega-market-sim/extern/vega/core/collateral/engine.go:646 +0x84c
code.vegaprotocol.io/vega/core/collateral.(*Engine).FinalSettlement(0x140014cd050, {0x1041cff80, 0x14009b04690}, {0x14003cd5040, 0x40}, {0x14002328900, 0x2a, 0x42})
        /Users/tom/Code/vega-market-sim/extern/vega/core/collateral/engine.go:829 +0x19cc
code.vegaprotocol.io/vega/core/execution/future.(*Market).closeMarket(0x14003aa2a00, {0x1041cff80, 0x14009b04690}, {0x1400012a078?, 0x14005ff4848?, 0x0?})
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:837 +0x1a4
code.vegaprotocol.io/vega/core/execution/future.(*Market).settlementDataWithLock(0x14003aa2a00, {0x1041cff80, 0x14009b04690})
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:3349 +0x84
code.vegaprotocol.io/vega/core/execution/future.(*Market).settlementData(0x10?, {0x1041cff80?, 0x14009b04690?}, 0x2?)
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:3339 +0x108
code.vegaprotocol.io/vega/core/products.(*Future).updateSettlementData(0x14004118000, {0x1041cff80, 0x14009b04690}, {{0x1400e5c87d8?, 0x14006c0f8f0?, 0x14006c0f860?}, 0x14009b046c0?})
        /Users/tom/Code/vega-market-sim/extern/vega/core/products/future.go:254 +0x448
code.vegaprotocol.io/vega/core/oracles.(*Engine).BroadcastData(0x140015fc960, {0x1041cff80, 0x14009b04690}, {{0x1400e5c87d8?, 0x20?, 0x40?}, 0x14009b046c0?})
        /Users/tom/Code/vega-market-sim/extern/vega/core/oracles/engine.go:118 +0x63c
code.vegaprotocol.io/vega/core/processor.(*App).DeliverSubmitOracleData(0x1400147c000, {0x1041cff80, 0x14009b04690}, {0x1041f0870, 0x1400b240800})
        /Users/tom/Code/vega-market-sim/extern/vega/core/processor/abci.go:1704 +0x1cc
```

On version 3685d72393c74fc6b1ad1011a6be9cb7aaa3ff0a this error was encountered:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x101cfe4b0]

goroutine 58102 [running]:
code.vegaprotocol.io/vega/core/collateral.(*Engine).getLedgerEntries(0x14001536630, {0x104773470, 0x14008294360}, 0x14004327410)
        /Users/tom/Code/vega-market-sim/extern/vega/core/collateral/engine.go:2411 +0xc40
code.vegaprotocol.io/vega/core/collateral.(*Engine).clearRemainingLPFees(0x14001536630, {0x104773470, 0x14008294360}, {0x1400d238bc0, 0x40}, {0x1400d238800, 0x40}, 0x1)
        /Users/tom/Code/vega-market-sim/extern/vega/core/collateral/engine.go:2655 +0x5dc
code.vegaprotocol.io/vega/core/collateral.(*Engine).ClearMarket(0x14001536630, {0x104773470, 0x14008294360}, {0x1400d238bc0, 0x40}, {0x1400d238800, 0x40}, {0x1400f93d000, 0x1f, 0x1400070e000?}, ...)
        /Users/tom/Code/vega-market-sim/extern/vega/core/collateral/engine.go:2594 +0x2020
code.vegaprotocol.io/vega/core/execution/future.(*Market).cleanMarketWithState(0x14006fb6a00, {0x104773470, 0x14008294360}, 0x9)
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:829 +0x1f4
code.vegaprotocol.io/vega/core/execution/future.(*Market).closeMarket(0x14006fb6a00, {0x104773470, 0x14008294360}, {0x140001a8078?, 0x14004328848?, 0x0?})
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:899 +0x3fc
code.vegaprotocol.io/vega/core/execution/future.(*Market).settlementDataWithLock(0x14006fb6a00, {0x104773470, 0x14008294360})
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:3735 +0x84
code.vegaprotocol.io/vega/core/execution/future.(*Market).settlementData(0x10?, {0x104773470?, 0x14008294360?}, 0x2?)
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:3725 +0x108
code.vegaprotocol.io/vega/core/products.(*Future).updateSettlementData(0x1400bfcd290, {0x104773470, 0x14008294360}, {{0x1400ef13a10?, 0x14008120270?, 0x14008120210?}, 0x14008294390?})
        /Users/tom/Code/vega-market-sim/extern/vega/core/products/future.go:254 +0x448
code.vegaprotocol.io/vega/core/oracles.(*Engine).BroadcastData(0x140015ae810, {0x104773470, 0x14008294360}, {{0x1400ef13a10?, 0x20?, 0x40?}, 0x14008294390?})
        /Users/tom/Code/vega-market-sim/extern/vega/core/oracles/engine.go:118 +0x63c
code.vegaprotocol.io/vega/core/processor.(*App).DeliverSubmitOracleData(0x14000160300, {0x104773470, 0x14008294360}, {0x1047941f0, 0x140080bfbc0})
        /Users/tom/Code/vega-market-sim/extern/vega/core/processor/abci.go:1704 +0x1cc
```

In the attached zip, replay corresponds to the first error and replay-2 to the second
[replays.zip](https://github.com/vegaprotocol/vega/files/11960311/replays.zip)

### Expected behaviour

The core not crashing

### Steps to reproduce

Run replay files with the following command:

```bash
vega start --nodewallet-passphrase-file=/path/to/file --home=/path/to/home --blockchain.nullchain.replay --blockchain.nullchain.replay-file=/path/to/replay
```

### Software version

3685d72393c74fc6b1ad1011a6be9cb7aaa3ff0a

**Comment by TomMcL** [comment]
This appears to still be an issue as-of commit `7736dd157a2077958f07d65ca3cf371183050730`

```
panic: settlement balance is not zero

goroutine 20115 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x0?, 0x1?, {0x1?, 0x0?, 0x0?})
        /Users/tom/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x7c
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x14011708680, {0x140014fd500, 0x1, 0x1})
        /Users/tom/go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x2ac
go.uber.org/zap.(*Logger).Panic(0x2?, {0x1032aac64?, 0x0?}, {0x140014fd500, 0x1, 0x1})
        /Users/tom/go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x54
code.vegaprotocol.io/vega/core/collateral.(*Engine).CheckLeftOverBalance(0x140019858c0, {0x10446c9a0, 0x140010e8450}, 0x14014a4d9a0, {0x1400c9ee380, 0x2c, 0x40?}, {0x1400cec0c40, 0x40})
        /Users/tom/Code/vega-market-sim/extern/vega/core/collateral/engine.go:834 +0x7b0
code.vegaprotocol.io/vega/core/collateral.(*Engine).FinalSettlement(0x140019858c0, {0x10446c9a0, 0x140010e8450}, {0x1400cec0fc0, 0x40}, {0x1400c9ee380, 0x2c, 0x37})
        /Users/tom/Code/vega-market-sim/extern/vega/core/collateral/engine.go:1017 +0x1718
code.vegaprotocol.io/vega/core/execution/future.(*Market).closeMarket(0x1400d208000, {0x10446c9a0, 0x140010e8450}, {0x188?, 0x51?, 0x0?}, 0x6?)
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:882 +0x198
code.vegaprotocol.io/vega/core/execution/future.(*Market).settlementDataWithLock(0x1400d208000, {0x10446c9a0, 0x140010e8450}, 0x9, 0x1401793f6a0)
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:3870 +0x8c
code.vegaprotocol.io/vega/core/execution/future.(*Market).settlementData(0x1400d208000, {0x10446c9a0, 0x140010e8450}, 0x2?)
        /Users/tom/Code/vega-market-sim/extern/vega/core/execution/future/market.go:3860 +0x194
code.vegaprotocol.io/vega/core/products.(*Future).updateSettlementData(0x1400ced4510, {0x10446c9a0, 0x140010e8450}, {{0x1401a4a2b20, 0x1, 0x1}, 0x140010e8480, 0x0})
        /Users/tom/Code/vega-market-sim/extern/vega/core/products/future.go:254 +0x450
code.vegaprotocol.io/vega/core/oracles.(*Engine).BroadcastData(0x14000595810, {0x10446c9a0, 0x140010e8450}, {{0x1401a4a2b20, 0x1, 0x1}, 0x140010e8480, 0x0})
        /Users/tom/Code/vega-market-sim/extern/vega/core/oracles/engine.go:131 +0x5a4
code.vegaprotocol.io/vega/core/processor.(*App).DeliverSubmitOracleData(0x14000658900, {0x10446c9a0, 0x140010e8450}, {0x104492ff0, 0x1401896a840})
        /Users/tom/Code/vega-market-sim/extern/vega/core/processor/abci.go:1741 +0x1e0
code.vegaprotocol.io/vega/core/processor.(*App).S
[replay.zip](https://github.com/vegaprotocol/vega/files/12048514/replay.zip)
endTransactionResult.func1({0x10446c9a0, 0x140010e8450}, {0x104492ff0, 0x1401896a840})
        /Users/tom/Code/vega-market-sim/extern/vega/core/processor/abci.go:486 +0x40
```

[replay.zip](https://github.com/vegaprotocol/vega/files/12048515/replay.zip)

**Comment by TomMcL** [comment]
Adding an entire vegahome zip

[vegahome.zip](https://github.com/vegaprotocol/vega/files/12111397/vegahome.zip)
