### ISSUE TITLE
[Bug]: Consensus failure when submitting stop orders

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#8721]
### Problem encountered

Received a consensus failure when submitting a stop order.

### Observed behaviour

Received a consensus failure when submitting a stop order.

### Expected behaviour

No failure

### Steps to reproduce

```bash
Details later
```

### Software version

vega - develop

### Relevant log output

```shell
2023-07-07T14:38:16.508+0100    ERROR   tendermint  consensus/state.go:732  CONSENSUS FAILURE!!!    {"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 156 [running]:\nruntime/debug.Stack()\n\t/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/debug/stack.go:24 +0x64\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x44\npanic({0x103c9dac0, 0x105e3de10})\n\t/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:884 +0x204\ncode.vegaprotocol.io/vega/core/execution/stoporders.(*Pool).RemoveExpired(0x14015632b40, {0x14018f8ca60, 0x2, 0x0?})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/execution/stoporders/stop_orders.go:241 +0x180\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).removeExpiredStopOrders(0x14015078500, {0x1042a49c8, 0x14013917d40}, 0x14013125b80?, {0x104273460, 0x1401324df98})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/execution/future/market.go:3443 +0x148\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).OnTick(0x14015078500, {0x1042a49c8, 0x14013917d40}, {0x40?, 0x14018dd0480?, 0x0?})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/execution/future/market.go:664 +0x3d8\ncode.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0x140002cab40, {0x1042a49c8, 0x14013917d40}, {0x1?, 0x1042c28e8?, 0x0?})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/execution/engine.go:1036 +0x390\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/vegatime/service.go:104\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0x1400042e400, {0x1042a49c8, 0x14013917d40}, {0x40?, 0x103b41780?, 0x0?})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/vegatime/service.go:77 +0x278\ncode.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0x14011e56720, 0x20, 0x20}, {{0xb, 0x1}, {0x14010dec090, 0xb}, 0x8b9, {0xee9f670, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/processor/abci.go:802 +0x554\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0x14011e56720, 0x20, 0x20}, {{0xb, 0x1}, {0x14010dec090, 0xb}, 0x8b9, {0xee9f670, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/blockchain/abci/abci.go:46 +0x60\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).BeginBlock(_, {{0x14011e56720, 0x20, 0x20}, {{0xb, 0x1}, {0x14010dec090, 0xb}, 0x8b9, {0xee9f670, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/cmd/vega/commands/node/app_wrapper.go:64 +0x4c\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0x14011e56720, 0x20, 0x20}, {{0xb, 0x1}, {0x14010dec090, 0xb}, 0x8b9, {0xee9f670, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/abci/client/local_client.go:280 +0x108\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0x14011e56720, 0x20, 0x20}, {{0xb, 0x1}, {0x14010dec090, 0xb}, 0x8b9, {0xee9f670, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/proxy/app_conn.go:81 +0x4c\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x1042a2d90?, 0x1400000ec40}, {0x1042b9580, 0x140013c4270}, 0x1400da77a40, {0x1042cba88, 0x1400000c588}, 0x8b8?)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:307 +0x2b8\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0x1400ccb2f40, 0x7}}, {0x1400ccb2f50, 0xb}, 0x1, 0x8b8, {{0x14012a06580, ...}, ...}, ...}, ...)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0xe4\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x1400ce5a000, 0x8b9)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1661 +0x94c\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x1400ce5a000, 0x8b9)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1570 +0x288\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1505 +0xa0\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0x1400ce5a000, 0x8b9, 0x0)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1543 +0xb8c\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0x1400ce5a000, 0x140103e4780, {0x14000075ef0, 0x28})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2165 +0x1678\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x1400ce5a000, 0x140103e4780, {0x14000075ef0?, 0x14001423380?})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x28\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x1400ce5a000, {{0x1042802e0?, 0x1401222db00?}, {0x14000075ef0?, 0x0?}})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x108\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x1400ce5a000, 0x0)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x2bc\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0xf4\n"}
```

**Comment by MuthuVega** [comment]
More details to be updated later 

Got the error locally , will try and reproduce on Jenkins and update ticket.
