### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by raven428** [vegaprotocol/vega#8746]
### Problem encountered

`data-node` is crashing when requesting `curl -s http://127.0.0.1:3008/api/v2/networkhistory/segments` or even `curl -s http://127.0.0.1:3008/api/v2/networkhistory` while `NetworkHistory.Enabled = false` in `config.toml`

### Observed behaviour

`data-node` is crashing when requesting `curl -s http://127.0.0.1:3008/api/v2/networkhistory/segments` or even `curl -s http://127.0.0.1:3008/api/v2/networkhistory` while `NetworkHistory.Enabled = false` in `config.toml`

### Expected behaviour

`data-node` shouldn't crash at these requests with some rejected answer

### Steps to reproduce

```bash
1. configure and start `data-node` i.e. from network history
2. set `NetworkHistory.Enabled = false` in `config.toml`
3. restart `data-node` with new configuration
4. perform request `curl -s http://127.0.0.1:3008/api/v2/networkhistory/segments`
5. observe the crash log bellow
```

### Software version

Vega Datanode CLI v0.71.6 (7a23f5e2f0fb4981c8318253142e2e23e3aa4f7c)

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0x1b5cd94]
goroutine 250 [running]:
code.vegaprotocol.io/vega/datanode/networkhistory.(*Service).ListAllHistorySegments(0x2e22b95?)
        /home/runner/work/vega/vega/datanode/networkhistory/service.go:161 +0x14
code.vegaprotocol.io/vega/datanode/api.(*TradingDataServiceV2).ListAllNetworkHistorySegments(0xc0023a94a0, {0xc003d843e3, 0xc001221300}, 0x4e99820)
        /home/runner/work/vega/vega/datanode/api/trading_data_v2.go:3433 +0x94
code.vegaprotocol.io/vega/protos/data-node/api/v2._TradingDataService_ListAllNetworkHistorySegments_Handler.func1({0x33ee1a0, 0xc003d94f00}, {0x28f2f80?, 0xc003d94ea0})
        /home/runner/work/vega/vega/protos/data-node/api/v2/trading_data_grpc.pb.go:3913 +0x7b
code.vegaprotocol.io/vega/datanode/ratelimit.(*RateLimit).GRPCInterceptor(0xc000852140, {0x33ee1a0, 0xc003d94f00}, {0x28f2f80, 0xc003d94ea0}, 0x0?, 0xc003d67ea8)
        /home/runner/work/vega/vega/datanode/ratelimit/ratelimit.go:184 +0x727
google.golang.org/grpc.getChainUnaryHandler.func1({0x33ee1a0, 0xc003d94f00}, {0x28f2f80, 0xc003d94ea0})
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1163 +0xb9
code.vegaprotocol.io/vega/datanode/api.headersInterceptor.func1({0x33ee1a0, 0xc003d94f00}, {0x28f2f80, 0xc003d94ea0}, 0xc003d81280?, 0xc003d63880)
        /home/runner/work/vega/vega/datanode/api/server.go:333 +0x4f2
google.golang.org/grpc.getChainUnaryHandler.func1({0x33ee1a0, 0xc003d94f00}, {0x28f2f80, 0xc003d94ea0})
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1163 +0xb9
code.vegaprotocol.io/vega/datanode/api.remoteAddrInterceptor.func1({0x33ee1a0, 0xc003d94e70}, {0x28f2f80, 0xc003d94ea0}, 0xc003d81280, 0xc003d63840)
        /home/runner/work/vega/vega/datanode/api/server.go:289 +0xef
google.golang.org/grpc.chainUnaryInterceptors.func1({0x33ee1a0, 0xc003d94e70}, {0x28f2f80, 0xc003d94ea0}, 0xc0008bfa20?, 0x279b680?)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1154 +0x8f
code.vegaprotocol.io/vega/protos/data-node/api/v2._TradingDataService_ListAllNetworkHistorySegments_Handler({0x2c56140?, 0xc0023a94a0}, {0x33ee1a0, 0xc003d94e70}, 0xc00024>
        /home/runner/work/vega/vega/protos/data-node/api/v2/trading_data_grpc.pb.go:3915 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0023a92c0, {0x3403f60, 0xc000976ea0}, 0xc003d570e0, 0xc0008c19b0, 0x4c052d0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0023a92c0, {0x3403f60, 0xc000976ea0}, 0xc003d570e0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.52.0/server.go:963 +0x28a
```

**Comment by gordsport** [comment]
@raven428 

This issue has been fixed and is a duplicate - fixed as per this comment

https://github.com/vegaprotocol/vega/issues/8633#issuecomment-1617858943
