### ISSUE TITLE
[Bug]: Consensus failure when submitting stop orders

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#8747]
### Problem encountered

Consensus failure when submitting stop orders

### Observed behaviour

Consensus failure when submitting stop orders

### Expected behaviour

No consensus failure should occur.

### Steps to reproduce

```bash
Unable to reproduce, tried many times but no luck.
```

### Software version

vega - 600157f9c08ce86bd36430328b164c1378aebd3f

### Failing test

n/a

### Jenkins run

n/a

### Relevant log output

```shell
CONSENSUS FAILURE!!!	{"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 345 [running]:\nruntime/debug.Stack()\n\t/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/debug/stack.go:24 +0x64\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x44\npanic({0x10706fb40, 0x109242aa0})\n\t/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:884 +0x204\ncode.vegaprotocol.io/vega/core/execution/stoporders.(*Pool).RemoveExpired(0x14016d02840, {0x14011e31d80, 0x2, 0x0?})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/execution/stoporders/stop_orders.go:241 +0x180\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).removeExpiredStopOrders(0x140126d0c80, {0x1076805a8, 0x140161e5a10}, 0x1401910dbc0?, {0x10764eb20, 0x14016882678})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/execution/future/market.go:3510 +0x148\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).OnTick(0x140126d0c80, {0x1076805a8, 0x140161e5a10}, {0x40?, 0x14013af5e60?, 0x0?})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/execution/future/market.go:666 +0x3d8\ncode.vegaprotocol.io/vega/core/execution.(*Engine).OnTick(0x140002d0b40, {0x1076805a8, 0x140161e5a10}, {0x1?, 0x10769e648?, 0x0?})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/execution/engine.go:1077 +0x390\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/vegatime/service.go:104\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0x14000290700, {0x1076805a8, 0x140161e5a10}, {0x40?, 0x106f111e0?, 0x0?})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/vegatime/service.go:77 +0x278\ncode.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0x14016657480, 0x20, 0x20}, {{0xb, 0x1}, {0x14011935cd0, 0xb}, 0x4234, {0xfa22e98, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/processor/abci.go:802 +0x554\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0x14016657480, 0x20, 0x20}, {{0xb, 0x1}, {0x14011935cd0, 0xb}, 0x4234, {0xfa22e98, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/core/blockchain/abci/abci.go:46 +0x60\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).BeginBlock(_, {{0x14016657480, 0x20, 0x20}, {{0xb, 0x1}, {0x14011935cd0, 0xb}, 0x4234, {0xfa22e98, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/muthu/vega/repos/vega/cmd/vega/commands/node/app_wrapper.go:64 +0x4c\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0x14016657480, 0x20, 0x20}, {{0xb, 0x1}, {0x14011935cd0, 0xb}, 0x4234, {0xfa22e98, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/abci/client/local_client.go:280 +0x108\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0x14016657480, 0x20, 0x20}, {{0xb, 0x1}, {0x14011935cd0, 0xb}, 0x4234, {0xfa22e98, ...}, ...}, ...})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/proxy/app_conn.go:81 +0x4c\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x10767ea50?, 0x14000390828}, {0x1076951d0, 0x14001025230}, 0x140162f6d20, {0x1076a77e8, 0x140003597d0}, 0x4233?)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:307 +0x2b8\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0x14000633b70, 0x7}}, {0x14000633b80, 0xb}, 0x1, 0x4233, {{0x140190feec0, ...}, ...}, ...}, ...)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0xe4\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x14001767880, 0x4234)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1661 +0x94c\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x14001767880, 0x4234)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1570 +0x288\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1505 +0xa0\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0x14001767880, 0x4234, 0x0)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1543 +0xb8c\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0x14001767880, 0x14010734e60, {0x14000074b70, 0x28})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2165 +0x1678\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x14001767880, 0x14010734e60, {0x14000074b70?, 0x1400dc1ad30?})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x28\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x14001767880, {{0x10765bc00?, 0x1400f2e1998?}, {0x14000074b70?, 0x0?}})\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x108\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x14001767880, 0x0)\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x2bc\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/Users/muthupandianvadivelu/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0xf4\n"}
```

**Comment by jeremyletang** [comment]
fixed in: https://github.com/vegaprotocol/vega/pull/8722
