### ISSUE TITLE
[Bug]: Consensus failure on fairground (n06&n07 nodes)

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#9038]
### Problem encountered

 there is full mempool on n06.testnet.vega.rocks and a panic from the CNSENSUS:
 
 ```
Aug 09 14:46:19 n06.testnet.vega.rocks visor[924169]: 2023-08-09T14:46:19.461Z        ERROR        tendermint        consensus/state.go:732        CONSENSUS FAILURE!!!        {"err": "+2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected F137FC4B696E4580C0D463F8608768D56D8171F6C911510E681C162639034789, got 31B92A9D016D4F12AB11C78292A4B0B7A1651E98F433EB185078CA86D7E150FD", "stack": "goroutine 9817872 [running]:
runtime/debug.Stack()
\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
\t/home/fryderyk/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c
panic({0x2fa7e20, 0xc01186d480})
\t/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc027e3a380, 0x9279ee)
\t/home/fryderyk/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1601 +0x1105
github.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc027e3a380, 0x9279ee)
\t/home/fryderyk/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1570 +0x2ff
github.com/tendermint/tendermint/consensus.(*State).handleCompleteProposal(0xc027e3a380, 0x42a?)
\t/home/fryderyk/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1957 +0x399
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc027e3a380, {{0x3e06740?, 0xc02b466990?}, {0xc02a838240?, 0x0?}})
\t/home/fryderyk/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:842 +0x290
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc027e3a380, 0x0)
\t/home/fryderyk/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x3f9
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
\t/home/fryderyk/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0x12d
"}
```

### Observed behaviour

Mem pool is full and network is not getting forward

### Expected behaviour

Node is moving forward

### Steps to reproduce

```bash
Not sure how to reproduce it but n06 & n07 is in broken state atm.
```

### Software version

https://github.com/vegaprotocol/vega/compare/v0.72.6...fix-non-determinism/v0.72.6+RollbackParentELS

**Comment by daniel1302** [comment]
[vega-full-mempool.log](https://github.com/vegaprotocol/vega/files/12311129/vega-full-mempool.log)

**Comment by wwestgarth** [comment]
Reproduced in in a system test here:
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/91685/pipeline/546

I think the issue is that in `preVoteClosedProposal()` for market proposals we put the proposal in both the active and enacted slices. When we restore from a snapshot that pointer link is lost. 

Up until now this has been fine because for markets once its `PASSED` there is no way for it become rejected _untill now_. With successor markets a passed proposal can become rejected if the parent market becomes succeeded by something else. In this case we change the proposal state which for non-restored nodes changes it in the enacted and active slices, for restored nodes _only the proposal in the active slice is updated_.
