### ISSUE TITLE
Soak test panic with SLA markets

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9051]
vega feature/integrate-sla-rebased-2
ST 2542db040834b2af0d35a6d6e54e5b295e309880

Smoke Test Run
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/91959/artifact/
```

goroutine 160 [running]:
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1.1()
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:154 +0x59
panic({0x46eea00, 0xc00039a8d0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/tendermint/tendermint/consensus.assertAppHashEqualsOneFromBlock({0xc000f7b820, 0x20, 0x20}, 0xc0016cc000)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:515 +0x10d
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x1}, {0xc0016b4e70, 0x7}}, {0xc0016b4e80, 0xb}, 0x1, 0x378, {{0xc002c165e0, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:468 +0x1fd
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x1}, {0xc0016b4e70, 0x7}}, {0xc0016b4e80, 0xb}, 0x1, 0x378, {{0xc002c165e0, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:393 +0x479
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0010b2d80, {0x578e2e8, 0xc0013651e0})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x1}, {0xc0016b4e70, 0x7}}, {0xc0016b4e80, 0xb}, 0x1, 0x378, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000307680, {0x575d6d0, 0xc0016fbf40}, 0xc000120300, {0x5741720, 0xc001c93668}, 0x0?, 0x0?, 0xc000120340, {0x5762df0, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/node/node.go:779 +0x597
code.vegaprotocol.io/vega/core/blockchain/abci.NewTmNode({{0x0}, 0x1, 0x1, 0x0, 0x0, {0xc0016645a0, 0xa}, {{0x0}, {0xc000161e60, 0x15}}, ...}, ...)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/tm_node.go:83 +0x725
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).startABCI(0xc0002b5000, 0x1953ab0?, {0x5787e60, 0xc0016ab4a0}, {0x7ffec61fd15d, 0x53}, {0x0?, 0xc0003c0690?}, {0x0, 0x0})
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:426 +0x1b6
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).startBlockchain(0xc0002b5000, 0x100000000000000?, {0x7ffec61fd15d?, 0x0?}, {0x0, 0x0}, {0x0, 0x0})
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:313 +0x3ab
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1()
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:157 +0x99
created by code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:148 +0x72f
	```

**Comment by gordsport** [comment]
could be related  to:

- https://github.com/vegaprotocol/vega/issues/9061

**Comment by vega-paul** [comment]
Latest occurrence
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/92671/testReport/(root)/run/testReport/(root)/run/artifact/soak-test/err-node-396.log

```
goroutine 160 [running]:
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1.1()
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:154 +0x59
panic({0x46ee9a0, 0xc002b1d830})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/tendermint/tendermint/consensus.assertAppHashEqualsOneFromBlock({0xc0006c7380, 0x20, 0x20}, 0xc0024cb680)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:515 +0x10d
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x1}, {0xc002654500, 0x7}}, {0xc002654510, 0xb}, 0x1, 0x355, {{0xc0024f6900, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:468 +0x1fd
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x1}, {0xc002654500, 0x7}}, {0xc002654510, 0xb}, 0x1, 0x355, {{0xc0024f6900, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:393 +0x479
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000176d80, {0x578e3c8, 0xc00265ab60})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x1}, {0xc002654500, 0x7}}, {0xc002654510, 0xb}, 0x1, 0x355, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0006ef900, {0x575d7b0, 0xc0028d9220}, 0xc002b1d410, {0x5741800, 0xc0029befa8}, 0x0?, 0x0?, 0xc002b1d450, {0x5762ed0, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/node/node.go:779 +0x597
code.vegaprotocol.io/vega/core/blockchain/abci.NewTmNode({{0x0}, 0x1, 0x1, 0x0, 0x0, {0xc000ed36a0, 0xa}, {{0x0}, {0xc001743e90, 0x15}}, ...}, ...)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/tm_node.go:83 +0x725
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).startABCI(0xc0002b4000, 0x0?, {0x5787f40, 0xc0029d4520}, {0x7ffec6f5812d, 0x53}, {0x0?, 0x0?}, {0x0, 0x0})
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:426 +0x1b6
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).startBlockchain(0xc0002b4000, 0x0?, {0x7ffec6f5812d?, 0x0?}, {0x0, 0x0}, {0x0, 0x0})
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:313 +0x3ab
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1()
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:157 +0x99
created by code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:148 +0x72f
```

**Comment by Sohill-Patel** [comment]
Latest soak test failure, the error looks different so it might just be a new issue. Please let me know and i will reopen my ticket https://github.com/vegaprotocol/vega/issues/9071

```
panic: block.AppHash does not match AppHash after replay. Got B638313FF249C9833B7B419CA80BA91055B4F88A7B002C8EE22D3714169DC8B2, expected 77E2E6A78B6CA29C67070EB308DD751D82AFAA6BEFCF70B0DC1861584BE474DB.

Block: Block{
  Header{
    Version:        {11 1}
    ChainID:        testnet-001
    Height:         245
    Time:           2023-08-15 14:03:47.586753633 +0000 UTC
    LastBlockID:    B158182127CB0A96286F093388FC10268B92AE4FD1EBCC08CBB5611A2A1E5113:1:0DE501734874
    LastCommit:     C71A3947C694E6BF1569480AEC779B73D3F0C25D55DE23081D8B3EA70C2E8312
    Data:           E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Validators:     65B73F957ACCE39F13DD4F500B4110CE199805F491FD8EAFC9FA9B022822E559
    NextValidators: 65B73F957ACCE39F13DD4F500B4110CE199805F491FD8EAFC9FA9B022822E559
    App:            77E2E6A78B6CA29C67070EB308DD751D82AFAA6BEFCF70B0DC1861584BE474DB
    Consensus:      C8CD39A92B22597AC33565A59990B4D1E440B15621B5E932D1D5B39A8F45E9DB
    Results:        E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Evidence:       E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Proposer:       1169B73C3918BE4A1EB47E7CEF2CDB4AADAC8A82
  }#8FF71C8BA7658D3B978C782815A98017CD519D435A8C62515F50FFC454AA5BE5
  Data{
    
  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  EvidenceData{
    
  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  Commit{
    Height:     244
    Round:      1
    BlockID:    B158182127CB0A96286F093388FC10268B92AE4FD1EBCC08CBB5611A2A1E5113:1:0DE501734874
    Signatures:
      CommitSig{DA75E3C5FC7F by 1169B73C3918 on 2 @ 2023-08-15T14:03:47.686727329Z}
      CommitSig{743FA52B0151 by 375F5B16B73B on 2 @ 2023-08-15T14:03:47.586753633Z}
  }#C71A3947C694E6BF1569480AEC779B73D3F0C25D55DE23081D8B3EA70C2E8312
}#8FF71C8BA7658D3B978C782815A98017CD519D435A8C62515F50FFC454AA5BE5
 [recovered]
	panic: block.AppHash does not match AppHash after replay. Got B638313FF249C9833B7B419CA80BA91055B4F88A7B002C8EE22D3714169DC8B2, expected 77E2E6A78B6CA29C67070EB308DD751D82AFAA6BEFCF70B0DC1861584BE474DB.

```
