### ISSUE TITLE
[Bug]: Data node snapshot panic

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#9065]
### Problem encountered

The data node panics during the full test run.

### Observed behaviour

Data node panics

### Expected behaviour

Data node should not panic

### Steps to reproduce

```bash
1. Do the full test run.
Unclear if reproducible.
```

### Software version

1943432df81b7dbd4b8103fd386ee7e32bcf4745

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/92226/

### Relevant log output

```shell
panic: failed to snapshot data

goroutine 1250335 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc0054605e0?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc001728750, {0xc00275e9c0, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc0012fd470?, {0x511ffbe?, 0x9?}, {0xc00275e9c0, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).createNewSnapshot.func4()
	/jenkins/workspace/common/system-tests-wrapper/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:117 +0x2a5
created by code.vegaprotocol.io/vega/datanode/networkhistory/snapshot.(*Service).createNewSnapshot
	/jenkins/workspace/common/system-tests-wrapper/vega/datanode/networkhistory/snapshot/service_create_snapshot.go:122 +0xa45
```

**Comment by wwestgarth** [comment]
The full error is:
```
failed to snapshot data	{"error": "failed to copy current state table data:failed to execute copy: failed to execute copy sql copy (select * from assets order by id, vega_time) TO STDOUT WITH (FORMAT csv, HEADER) : FATAL: terminating connection due to administrator command (SQLSTATE 57P01)"}
```
where this bit `terminating connection due to administrator command` means that postgres itself has killed the transaction to copy the table state. Times I've seen this before is when something infrastructure-y has happened.

The time difference between the start of the copy and the abort is very small is ~tenth-of-a-second which means the copy hasn't frozen or gotten stuck, so its not a timeout or anything:
```
2023-08-14T13:11:13.397Z	INFO	datanode.networkHistory.snapshot	snapshot/service_create_snapshot.go:115	copying all table data....
2023-08-14T13:11:13.532Z	PANIC	datanode.networkHistory.snapshot	snapshot/service_create_snapshot.go:117	failed to snapshot data
```

This all happens after the tests have completed at roughly `13:10:52.001`. I feel this is likely a jenkins thing. Worst case is that there is an issue with the data-node shutting down gracefully but from the logs there is no indication the data-node had even received the signal.

**Comment by gordsport** [comment]
@wwestgarth - based on the above can we close this issue?

**Comment by jgsbennett** [comment]
@mkjmdski did mention something about upgrading agent drive space? I wonder if that might have been the issue, then.

**Comment by wwestgarth** [comment]
It has not come up again and happened during Jenkins tweaks, so its not a core bug.
