### ISSUE TITLE
SLA runtime error: invalid memory address or nil pointer dereference (goroutine 353)

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9066]
```
{"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 353 {"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 268 [running]:\nruntime/debug.Stack()
/opt/homebrew/Cellar/go@1.19/1.19.10/libexec/src/runtime/debug/stack.go:24 +0x64\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x44\npanic({0x103cf2080, 0x106134ae0})
/opt/homebrew/Cellar/go@1.19/1.19.10/libexec/src/runtime/panic.go:884 +0x204\ncode.vegaprotocol.io/vega/core/execution/common.(*MarketLiquidity).CancelLiquidityProvision(0x1400110dc20, {0x10433feb0, 0x14005787b30}, {0x14004b8eb80, 0x40})
/Users/paulwebb/repos/vega/core/execution/common/liquidity_provision.go:589 +0xbc\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).CancelLiquidityProvision(0x103cafee0?, {0x10433feb0?, 0x14005787b30?}, 0x40?, {0x14004b8eb80?, 0x179?})
/Users/paulwebb/repos/vega/core/execution/future/liquidity_provision.go:55 +0x64\ncode.vegaprotocol.io/vega/core/execution.(*Engine).CancelLiquidityProvision(0x1400029ea00, {0x10433feb0, 0x14005787b30}, 0x140019ed350, {0x14004b8eb80, 0x40})
/Users/paulwebb/repos/vega/core/execution/engine.go:1207 +0x390\ncode.vegaprotocol.io/vega/core/processor.(*App).DeliverCancelLiquidityProvision(0x1400047ec00, {0x10433feb0, 0x14005787b30}, {0x1043667d0, 0x14007894b00})
/Users/paulwebb/repos/vega/core/processor/abci.go:1674 +0x1d8\ncode.vegaprotocol.io/vega/core/processor.(*App).SendTransactionResult.func1({0x10433feb0, 0x14005787b30}, {0x1043667d0, 0x14007894b00})
/Users/paulwebb/repos/vega/core/processor/abci.go:486 +0x40\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).DeliverTx(0x14000344fd0, {{0x140084e0300, 0x179, 0x179}})
/Users/paulwebb/repos/vega/core/blockchain/abci/abci.go:140 +0x600\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).DeliverTx(0x1400859c560?, {{0x140084e0300?, 0x20?, 0xb?}})
/Users/paulwebb/repos/vega/cmd/vega/commands/node/app_wrapper.go:37 +0x4c\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0x14001a414a0, {{0x140084e0300?, 0x14001a414a0?, 0x1400162e2f8?}})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/abci/client/local_client.go:93 +0xf0\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0x1400859c560?, {{0x140084e0300?, 0x20?, 0xb?}})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/proxy/app_conn.go:85 +0x2c\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x10433e1d0?, 0x140006ac388}, {0x104354cc0, 0x14001053360}, 0x14003a07860, {0x104367478, 0x14000455f68}, 0xae?)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:320 +0x6f4\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0x14001658760, 0x7}}, {0x14001658770, 0xb}, 0x1, 0xae, {{0x14005c7a980, ...}, ...}, ...}, ...)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0xe4\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x140011cfc00, 0xaf)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1661 +0x94c\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x140011cfc00, 0xaf)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1570 +0x288\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1505 +0xa0\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0x140011cfc00, 0xaf, 0x0)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1543 +0xb8c\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0x140011cfc00, 0x1400c9197c0, {0x0, 0x0})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2165 +0x1678\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x140011cfc00, 0x1400c9197c0, {0x0?, 0x1009afaac?})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x28\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x140011cfc00, {{0x10431ada0?, 0x1400c4b5130?}, {0x0?, 0x0?}})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x108\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x140011cfc00, 0x0)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:788 +0x368\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0xf4\n"}
```

**Comment by vega-paul** [comment]
[visor-5-with-vega-data-node.stdout-2023-08-14T14:42:23+01:00.log.zip](https://github.com/vegaprotocol/vega/files/12336181/visor-5-with-vega-data-node.stdout-2023-08-14T14.42.23%2B01.00.log.zip)

**Comment by vega-paul** [comment]
[vega-full-2.stdout-2023-08-14T17:33:42+01:00.log.zip](https://github.com/vegaprotocol/vega/files/12337428/vega-full-2.stdout-2023-08-14T17.33.42%2B01.00.log.zip)
