### ISSUE TITLE
[Bug]: Consensus failure after protocol upgrade

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#9068]
### Problem encountered

Consensus failure during protocol upgrade tests in full run.

### Observed behaviour

Error as below encountered.

```
2023-08-14T12:21:22.490Z	ERROR	tendermint	consensus/state.go:732	CONSENSUS FAILURE!!!	{"err": "open /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/tendermint/node0/data/write-file-atomic-7638838507984997057: no such file or directory", "stack": "goroutine 207 [running]:\nruntime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c\npanic({0x4a31720, 0xc0002d2330})
/usr/local/go/src/runtime/panic.go:884 +0x213\ngithub.com/tendermint/tendermint/privval.(*FilePVLastSignState).Save(0x80?)
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/privval/file.go:137 +0x90\ngithub.com/tendermint/tendermint/privval.(*FilePV).saveSigned(0x53d7b816562dc85c?, 0xcf0116b9e3caf74a?, 0x43b31f8?, 0xc0?, {0xc0016fc500?, 0x4e10abb3121739c5?, 0x53d7b816562dc85c?}, {0xc005f09c40, 0x40, 0x40})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/privval/file.go:393 +0x88\ngithub.com/tendermint/tendermint/privval.(*FilePV).signVote(0xc0000e8280, {0xc000658880, 0xb}, 0xc0028eaa00)
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/privval/file.go:337 +0x2f6\ngithub.com/tendermint/tendermint/privval.(*FilePV).SignVote(0xc000d55c00?, {0xc000658880?, 0xbcaeac6d896448e6?}, 0xca049503a104a630?)
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/privval/file.go:254 +0x1e\ngithub.com/tendermint/tendermint/consensus.(*State).signVote(0xc000d55c00, 0x2, {0xc005f07540, 0x20, 0x20}, {0x0?, {0xc005f07560?, 0x0?, 0x0?}})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2214 +0x550\ngithub.com/tendermint/tendermint/consensus.(*State).signAddVote(0xc000d55c00, 0x2de?, {0xc005f07540, 0x20, 0x20}, {0xb?, {0xc005f07560?, 0x2dd?, 0xc005f06ca0?}})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2259 +0x225\ngithub.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc000d55c00, 0x2de, 0x0)
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1425 +0x1393\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000d55c00, 0xc0028ea460, {0xc0022559e0, 0x28})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2137 +0x13d8\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000d55c00, 0xc0028ea460, {0xc0022559e0?, 0xc0043b3c08?})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000d55c00, {{0x5800e60, 0xc002bbc650}, {0xc0022559e0, 0x28}})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x3ff\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000d55c00, 0x0)
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x3f0\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0x12d\n"}
```

### Expected behaviour

No consensus failure.

### Steps to reproduce

```bash
Observed this error in as part of an overnight full run.
Not too sure if this is reproducible.
```

### Software version

vega - develop

### Failing test

test_protocol_upgrade_nodes_wait_for_consensus

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/92231/testReport/

### Relevant log output

```shell
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/92231/artifact/testnet/logs/testnet-nodeset-validators-0-validator/vega-validator-0.stdout-2023-08-14T12%3A04%3A10Z.log/*view*/
```

**Comment by MuthuVega** [comment]
Note: This **MAYBE** related to ethereum oracles - not too sure as also saw the below error message in the logs.

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/92231/artifact/testnet/logs/testnet-nodeset-validators-0-validator/vega-validator-0.stdout-2023-08-14T12%3A04%3A10Z.log/*view*/

`2023-08-14T12:05:28.830Z	ERROR	core.protocol.event-forwarder.ethereum.log-filterer	ethereum/filterer.go:262	Couldn't subscribe to the Ethereum log filterer	{"from-block": "174", "to-block": "175", "addresses": ["0xdEcdA30fd3449718304eA201A8f220eBdE25dd1E"], "error": "Post \"http://127.0.0.1:8545/\": context canceled"}`

**Comment by gordsport** [comment]
@MuthuVega - can we consistently reproduce this issue?

**Comment by MuthuVega** [comment]
This issue was spotted as part of the overnight run, however , this hasn't happened and there isn't any way to reproduce this consistently. So closing issue until we see it again.
