### ISSUE TITLE
[Bug]: CONSENSUS FAILURE "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#9090]
### Problem encountered

```
tests/API/test_liquidity_providers.py:59: AssertionError
-------------------- STACK FOUND IN VEGA LOGS. STACK 1 of 3 --------------------
2023-08-15T17:02:19.134Z	ERROR	tendermint	consensus/state.go:732	CONSENSUS FAILURE!!!	{"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 195 [running]:\nruntime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c\npanic({0x48d62c0, 0x743a470})
/usr/local/go/src/runtime/panic.go:884 +0x213\ncode.vegaprotocol.io/vega/core/execution/common.(*MarketLiquidity).syncPartyCommitmentWithBondAccount(0xc001544240, {0x5765d50, 0xc0052d38c0}, {0xc0043cd2e0, 0x2, 0x2})
/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/common/liquidity_provision.go:282 +0xa42\ncode.vegaprotocol.io/vega/core/execution/common.(*MarketLiquidity).OnEpochStart(0xc001544240, {0x5765d50, 0xc0052d38c0}, {0x0?, 0x0?, 0x0?}, 0x0?, 0x0?, 0x0?, {0xc0031fc9e0, ...})
/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/common/liquidity_provision.go:296 +0xd0\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).OnEpochEvent(0xc002c6b200, {0x5765d50, 0xc0052d38c0}, {0x26, {0x2d4b0601, 0xedc6da699, 0x0}, {0x2d4b0601, 0xedc6da69e, 0x0}, ...})
/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/future/market.go:339 +0x16e\ncode.vegaprotocol.io/vega/core/execution.(*Engine).OnEpochEvent(...)
/jenkins/workspace/common/system-tests-wrapper/vega/core/execution/engine.go:223\ncode.vegaprotocol.io/vega/core/epochtime.(*Svc).notify(0xc001377e60, {0x5765d50, 0xc0052d38c0}, {0x26, {0x2d4b0601, 0xedc6da699, 0x0}, {0x2d4b0601, 0xedc6da69e, 0x0}, ...})
/jenkins/workspace/common/system-tests-wrapper/vega/core/epochtime/service.go:201 +0xe5\ncode.vegaprotocol.io/vega/core/epochtime.(*Svc).OnTick(0xc001377e60, {0x5765d50, 0xc0052d38c0}, {0x1?, 0x5780118?, 0x0?})
/jenkins/workspace/common/system-tests-wrapper/vega/core/epochtime/service.go:142 +0x854\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).notify(...)
/jenkins/workspace/common/system-tests-wrapper/vega/core/vegatime/service.go:104\ncode.vegaprotocol.io/vega/core/vegatime.(*Svc).SetTimeNow(0xc000d96200, {0x5765d50, 0xc0052d38c0}, {0x40?, 0x46eeb00?, 0x0?})
/jenkins/workspace/common/system-tests-wrapper/vega/core/vegatime/service.go:77 +0x24f\ncode.vegaprotocol.io/vega/core/processor.(*App).OnBeginBlock(_, {{0xc003a0f3c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc004926780, 0xb}, 0x144, {0x2d4b0601, ...}, ...}, ...})
/jenkins/workspace/common/system-tests-wrapper/vega/core/processor/abci.go:779 +0x747\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).BeginBlock(_, {{0xc003a0f3c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc004926780, 0xb}, 0x144, {0x2d4b0601, ...}, ...}, ...})
/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/abci.go:46 +0x75\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).BeginBlock(_, {{0xc003a0f3c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc004926780, 0xb}, 0x144, {0x2d4b0601, ...}, ...}, ...})
/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/app_wrapper.go:64 +0x55\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc003a0f3c0, 0x20, 0x20}, {{0xb, 0x1}, {0xc004926780, 0xb}, 0x144, {0x2d4b0601, ...}, ...}, ...})
```

### Observed behaviour

concensus failure 

### Expected behaviour

no concensus failure 

### Steps to reproduce

```bash
1. Run the test test_liquidity_providers_api that will setup the scenario 
     - Market with lp commitment,  lp orders and trader orders to move it to continuous trading
     - New LP provision but no orders
2. Observe the error
```

### Software version

vega branch feature/integrate-sla-rebased-2

### Failing test

test_liquidity_providers_api

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/92900/testReport/junit/tests.API/test_liquidity_providers/test_liquidity_providers_api_market_object_new_market_object_traders_/

**Comment by Sohill-Patel** [comment]
known issue. fixed by https://github.com/vegaprotocol/vega/pull/9085/files
