### ISSUE TITLE
[CONSENSUSFailure]SLA Run

### ISSUE THREAD

**Issue by VanithaVega** [vegaprotocol/vega#9129]
Jenkins Run
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/94744/testReport/junit/tests.trading/liquidityProvision_test/test_DecreaseCommitSuffFunds/

test 
tests.trading.liquidityProvision_test.test_DecreaseCommitSuffFunds (from pytest)
CONSENSUS FAILURE was thrown when we run the tests

Barnch -
system-test -  sla-future-test-refactor

vega -feature/integrate-sla-rebased-2

```

Error Message
AssertionError: Unable to retrieve ListOrdersRequest within timeout=30 seconds ref_id='test_DecreaseCommitSuffFunds-f51730b2' order={}
assert {}
Stacktrace
context = {'AssetID': '57e0200a8c27e1253a7c41052dd06d95fa04f587973c493b1afc0f2a923d2dd1', 'MarketID': '0a154673070f303141e05b214..., 'governance.proposal.asset.maxEnact': '8760h0m0s', ...}, 'auction_volume_traders': ['DAAA84D3DB', '22FFB86725'], ...}
trader = '2E065E02E0', lp_trader = ['396C8A380D']
market = '0a154673070f303141e05b214e658dbc8d212f36026e26fd19ca97a629a6bc62'
liquidity_provision = <modules.lpMod.liqProvMod.LiquidityProvider object at 0x7f092619ab10>

    @pytest.mark.liquidity
    @pytest.mark.full
    def test_DecreaseCommitSuffFunds(context, trader, lp_trader, market, liquidity_provision):
        """
        LP can decrease their commitment and it will take affect immediately
        without incurring penalties (in open auction) (0044-LIME-051)
        """
    
        ruser = lp_trader[0]
    
        liquidity_provision.new_provision()
    
>       submit_matching_trades(context, market, trader, ruser, 1000, 1000)

tests/trading/liquidityProvision_test.py:150: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/trading/liquidityProvision_test.py:177: in submit_matching_trades
    ref1, ord1 = ordersMod.limit_order_submit(
modules/orderMod/ordersMod.py:119: in limit_order_submit
    ord_id = find_and_verify_order_event(
modules/orderMod/ordersMod.py:1241: in find_and_verify_order_event
    ord_id = Get_Order_ByRef(ordRef)["id"]  # https://github.com/vegaprotocol/vega/issues/5441
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

ref_id = 'test_DecreaseCommitSuffFunds-f51730b2', timeout = 30
assert_response = True

    def Get_Order_ByRef(ref_id, timeout=30, assert_response=True):
        order = {}
        now = time.time()
        while time.time() <= now + timeout:
            try:
                request = api.trd_v2.ListOrdersRequest(filter=api.trd_v2.OrderFilter(reference=str(ref_id)))
                response = api.grpc_stub_trd_data_v2.ListOrders(request)
                if len(response.orders.edges) == 0:
                    continue
                else:
                    # Note: there is nothing stopping multiple orders having the same reference; how
                    #       do we know we've got the one we want?
                    order = to_json(response.orders.edges[0].node)
                    break
            except IndexError or grpc.RpcError:
                time.sleep(0.2)
        if assert_response:
            if len(order) == 0:
                logging.info(f"Order not found via {ref_id=}")
>           assert order, f"Unable to retrieve ListOrdersRequest within {timeout=} seconds {ref_id=} {order=}"
E           AssertionError: Unable to retrieve ListOrdersRequest within timeout=30 seconds ref_id='test_DecreaseCommitSuffFunds-f51730b2' order={}
E           assert {}

modules/orderMod/ordersMod.py:1711: AssertionError
-------------------- STACK FOUND IN VEGA LOGS. STACK 1 of 3 --------------------
2023-08-18T08:08:50.681Z	ERROR	tendermint	consensus/state.go:732	CONSENSUS FAILURE!!!	{"err": "error while amending liquidity provision, this should not happen at this point, the LP was validated earlier", "stack": "goroutine 196 [running]:\nruntime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c\npanic({0x47c23a0, 0xc000d7e540})
/usr/local/go/src/runtime/panic.go:884 +0x213\ngo.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc0012ddb80?})
/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65\ngo.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00509cdd0, {0xc0033883c0, 0x1, 0x1})

```

**Comment by karlem** [comment]
@VanithaVega the test was using old commit hash. It has been possibly already fixed on Friday. Let's see here: https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/95771/

**Comment by karlem** [comment]
@VanithaVega is this still an issue?

**Comment by VanithaVega** [comment]
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/97482/
got a new branch with teh old commit and reran for consensus error. I didnt not hit error again.
