### ISSUE TITLE
[Bug]: Panic in system test run during checkpoint restart

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#9166]
### Problem encountered

[This test](https://jenkins.ops.vega.xyz/job/common/job/system-tests/27067/testReport/tests.newLnl/lnl_test/Call_tests___network_infra_a_o___test_treasury_account_balances_restored_after_network_restart/) appeared to suffer a panic restarting from checkpoint. Unclear what caused it, and to my knowledge the overnight run is clean right now. The test run was running on a branch which ought to have had zero impact on the tests, so this should effectively be the same as a develop test run. My view is that this is therefore likely some intermittent issue.

https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/97148/artifact/testnet/logs/testnet-nodeset-validators-0-validator/visor-0-with-vega.stderr-2023-08-22T15%3A59%3A59Z.log

### Observed behaviour

Vega panics during checkpoint restart

### Expected behaviour

Clean restart

### Steps to reproduce

```bash
Unknown. This happened during a full test run on https://github.com/vegaprotocol/system-tests/pull/2491/ ,   but on one of the child jobs that ought to have been unaffected by these changes.
```

### Software version

3e16a846ee23775d6fa4709223019e384d4b232d

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d8 pc=0x29db680]

goroutine 162 [running]:
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*blockTimeFetcher).fetchTimeByBlock(0x49df320?, {0x58dfe08?, 0xc001687630?}, 0x29d074c?)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/filterer.go:868 +0x80
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*blockTimeFetcher).TimeForBlock(0xc000e0dbf0, {0x58dfe08, 0xc001687630}, 0xc001730600?)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/filterer.go:847 +0x65
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*LogFilterer).FilterStakingEvents(0xc001529800, {0x58dfe08, 0xc001687630}, 0x1?, 0x0?, 0xc0013cef00)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/filterer.go:212 +0x1f8
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*Engine).gatherEvents(0xc001671490, {0x58dfe08, 0xc001687630})
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/engine.go:163 +0x159
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*Engine).Start.func1()
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/engine.go:132 +0x29e
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*poller).Loop(0xc0016a2258, 0xc000e0df60)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/engine.go:223 +0x6f
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*Engine).Start(0xc001671490)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/engine.go:124 +0xfd
code.vegaprotocol.io/vega/core/evtforward.(*Engine).Start.func1()
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/engine.go:146 +0x4a
created by code.vegaprotocol.io/vega/core/evtforward.(*Engine).Start
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/engine.go:144 +0x5d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1d8 pc=0x29db680]

goroutine 119 [running]:
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*blockTimeFetcher).fetchTimeByBlock(0x49df320?, {0x58dfe08?, 0xc001651400?}, 0x29d074c?)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/filterer.go:868 +0x80
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*blockTimeFetcher).TimeForBlock(0xc001867bf0, {0x58dfe08, 0xc001651400}, 0xc0018de280?)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/filterer.go:847 +0x65
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*LogFilterer).FilterStakingEvents(0xc00125e300, {0x58dfe08, 0xc001651400}, 0x1?, 0x0?, 0xc0014705d0)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/filterer.go:212 +0x1f8
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*Engine).gatherEvents(0xc0000eb7a0, {0x58dfe08, 0xc001651400})
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/engine.go:163 +0x159
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*Engine).Start.func1()
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/engine.go:132 +0x29e
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*poller).Loop(0xc001630af8, 0xc001867f60)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/engine.go:223 +0x6f
code.vegaprotocol.io/vega/core/evtforward/ethereum.(*Engine).Start(0xc0000eb7a0)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/ethereum/engine.go:124 +0xfd
code.vegaprotocol.io/vega/core/evtforward.(*Engine).Start.func1()
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/engine.go:146 +0x4a
created by code.vegaprotocol.io/vega/core/evtforward.(*Engine).Start
	/jenkins/workspace/common/system-tests-wrapper/vega/core/evtforward/engine.go:144 +0x5d
Error: maximum number of possible restarts has been reached: failed after waiting for binary /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/visor/visor0/current/vega [node --home /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/vega/node0 --tendermint-home /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/tendermint/node0 --nodewallet-passphrase-file /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/vega/node0/node-vega-wallet-pass.txt]: exit status 2
Usage:
  vegavisor run [flags]

Flags:
  -h, --help          help for run
      --home string   Path to visor home folder
```

**Comment by wwestgarth** [comment]
This was just me doing something silly. Will be fix once this is reverted:
https://github.com/vegaprotocol/vega/pull/9165
