### ISSUE TITLE
[Bug]: Consensus failure in the LNL after the protocol upgrade

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#9182]
### Problem encountered

We got a consensus failure for the LNL. The failure occurred on two data nodes (n14 and n15) on the following system-tests run: https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/641

The CONSENSUS FAILURE happened on the protocol upgrade block. We proposed protocol upgrade on height `293`

```
2023-08-23 07:55:40.882:[INFO] [MainProcess] [MainThread] [vega_commands.py]:[protocol_upgrade_proposal]:[1043] /jenkins/workspace/common/system-tests-lnl-mainnet/system-tests/../networkdata/testnet/../vega protocol_upgrade_proposal --home /jenkins/workspace/common/system-tests-lnl-mainnet/networkdata/testnet/vega/node0 --passphrase-file /jenkins/workspace/common/system-tests-lnl-mainnet/networkdata/testnet/vega/node0/node-vega-wallet-pass.txt --vega-release-tag v99.99.0+dev.0b7aaef4.modified --height 293 --output json
```

Then Consensus failure failed on block 294:

More logs from panic node is here: https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/641/artifact/testnet/logs/vega-mainnet-nodeset-full-14-full/visor-14-with-vega-data-node.stdout-2023-08-23T07%3A51%3A51Z.log

All validators were fine.

We can get snapshots from artifact:
- Broken data-node: https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/641/artifact/testnet/vega/node14/state/node/snapshots/
- One validator(without failure): https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/641/artifact/testnet/vega/node5/state/node/snapshots/

### Observed behaviour

Panic after protocol upgrade

### Expected behaviour

Protocol upgrade should not finish with panic

### Steps to reproduce

```bash
Trying to reproduce
```

### Software version

develop(0b7aaef43417f6e191093c9f48998dd57fd40576)

### Jenkins run

https://jenkins.ops.vega.xyz/job/common/job/system-tests-lnl-mainnet/641

### Configuration used

```shell
- 13 validators
- 3 data nodes
- Mainnet checkpoint loaded
```

### Relevant log output

```shell
2023-08-23T07:57:30.604Z	ERROR	tendermint	consensus/state.go:732	CONSENSUS FAILURE!!!	{"err": "precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected 595094F080532CD155DE5B42E9A3B663273BF9D350CC484D139FE716E0AF73E4, got D25D19A74613306D6E30D815E4390F3B01C18E2470E7A3816E8375587A2999F9", "stack": "goroutine 251 [running]:
runtime/debug.Stack()
\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c
panic({0x482d3a0, 0xc00fc315f0})
\t/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc014d5a380, 0x127, 0x0)
\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1414 +0x1699
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc014d5a380, 0xc00fea5ea0, {0xc0148463f0, 0x28})
\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2137 +0x13d8
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc014d5a380, 0xc00fea5ea0, {0xc0148463f0?, 0xc00f7edc08?})
\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x2c
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc014d5a380, {{0x58bbfc0, 0xc0107986c8}, {0xc0148463f0, 0x28}})
\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x3ff
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc014d5a380, 0x0)
\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x3f0
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
\t/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0x12d
"}
```
```

**Comment by gordsport** [comment]
resolved
