### ISSUE TITLE
[Bug]: Consensus failure "precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#9241]
### Problem encountered

2023-08-30T11:55:49.071Z	ERROR	tendermint	consensus/state.go:732	CONSENSUS FAILURE!!!	{"err": "precommit step; +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected 1647BF0DE9C1CFAD878442BE7558DDFBAF171A02BB82FBB2D9E2F26F2E3F1F5A, got E8456C195548B3E9FCD86238AAB32A824471DA149D6D553F6BC2A35A3AD9AD34", "stack": "goroutine 229 [running]:\nruntime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x4c\npanic({0x480ba60, 0xc0047aa590})
/usr/local/go/src/runtime/panic.go:884 +0x213\ngithub.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc001966700, 0x53, 0x7)
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1414 +0x1699\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc001966700, 0xc001730d20, {0xc00419d0e0, 0x28})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2137 +0x13d8\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc001966700, 0xc001730d20, {0xc00419d0e0?, 0xc001619c08?})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc001966700, {{0x5896360, 0xc003f221b0}, {0xc00419d0e0, 0x28}})
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x3ff\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc001966700, 0x0)
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x3f0\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart
/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0x12d\n"}

### Observed behaviour

consensus failure when proposing a future market

### Expected behaviour

no consensus failure

### Steps to reproduce

```bash
1. Full run of system-test, shows the consensus failure for test `test_liquidity_providers_accounts_during_protocol_upgrade`
```

### Software version

dev branch

### Failing test

test_liquidity_providers_accounts_during_protocol_upgrade

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests/219/testReport/junit/tests.protocol_upgrade/protocol_upgrade_test/Call_tests___network_infra_p_without_validators___test_liquidity_providers_accounts_during_protocol_upgrade_market_object_traders_/

**Comment by Sohill-Patel** [comment]
duplicate of https://github.com/vegaprotocol/vega/issues/9304

**Comment by Sohill-Patel** [comment]
duplicate of https://github.com/vegaprotocol/vega/issues/9304
