### ISSUE TITLE
Panic on VC startup

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9290]
Started VC locally on develop versions

```
Logs from failed testnet-nodeset-validators-0-validator job:
-------- visor-3-with-vega.stderr-2023-09-04T18:19:06+01:00.log:
-------- visor-4-with-vega.stderr-2023-09-04T18:19:06+01:00.log:
-------- visor-0-with-vega.stderr-2023-09-04T18:19:06+01:00.log:
panic: send on closed channel

goroutine 187 [running]:
code.vegaprotocol.io/vega/core/coreapi/services.(*NetParams).Push(0x140011df340, {0x140012e2a80?, 0x9f, 0x0?})
panic: send on closed channel

panic: send on closed channel

goroutine 234 [running]:
goroutine 213 [running]:
code.vegaprotocol.io/vega/core/coreapi/services.(*NetParams).Push(0x140011f6d80, {0x140003e1500?, 0x9f, 0x0?})
	/Users/paulwebb/repos/vega/core/coreapi/services/netparams.go:71 +0xc8
code.vegaprotocol.io/vega/core/coreapi/services.(*NetParams).Push(0x14001a31680, {0x1400170d500?, 0x9f, 0x0?})
	/Users/paulwebb/repos/vega/core/coreapi/services/netparams.go:71 +0xc8
code.vegaprotocol.io/vega/core/broker.(*Broker).startSending.func1(0x140012e95c0, 0x1a)
	/Users/paulwebb/repos/vega/core/broker/broker.go:224 +0x534
	/Users/paulwebb/repos/vega/core/coreapi/services/netparams.go:71 +0xc8
code.vegaprotocol.io/vega/core/broker.(*Broker).startSending.func1(0x140019f2360, 0x1a)
created by code.vegaprotocol.io/vega/core/broker.(*Broker).startSending
	/Users/paulwebb/repos/vega/core/broker/broker.go:198 +0x518
code.vegaprotocol.io/vega/core/broker.(*Broker).startSending.func1(0x1400036e240, 0x1a)
	/Users/paulwebb/repos/vega/core/broker/broker.go:224 +0x534
created by code.vegaprotocol.io/vega/core/broker.(*Broker).startSending
	/Users/paulwebb/repos/vega/core/broker/broker.go:224 +0x534
created by code.vegaprotocol.io/vega/core/broker.(*Broker).startSending
	/Users/paulwebb/repos/vega/core/broker/broker.go:198 +0x518
Error: maximum number of possible restarts has been reached: failed after waiting for binary /Users/paulwebb/repos/networkdata/testnet/visor/visor0/current/vega [node --home /Users/paulwebb/repos/networkdata/testnet/vega/node0 --tendermint-home /Users/paulwebb/repos/networkdata/testnet/tendermint/node0 --nodewallet-passphrase-file /Users/paulwebb/repos/networkdata/testnet/vega/node0/node-vega-wallet-pass.txt]: exit status 1
Error: maximum number of possible restarts has been reached: failed after waiting for binary /Users/paulwebb/repos/networkdata/testnet/visor/visor4/current/vega [node --home /Users/paulwebb/repos/networkdata/testnet/vega/node4 --tendermint-home /Users/paulwebb/repos/networkdata/testnet/tendermint/node4 --nodewallet-passphrase-file /Users/paulwebb/repos/networkdata/testnet/vega/node4/node-vega-wallet-pass.txt]: exit status 1
Usage:
```

**Comment by vega-paul** [comment]
currently not reproducible
