### ISSUE TITLE
[Bug]: Compiler panics when building the Go Binary 

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#9300]
### Problem encountered

A panic happened during the compilation of the VEGA core binary.  See details below

### Observed behaviour

Panic during compilation

### Expected behaviour

Vega can be compiled w/o panic

### Steps to reproduce

```bash
I was not able to reproduce it. I have rerun the pipeline for jenkins14 node and given vega branch - https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/4039/ - but it did not happen again
```

### Software version

806a8ae61fd34d97f8242ca417c9db134e28480b

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/3907/

### Configuration used

```shell
Go compiler version: go version go1.20 linux/amd64

Ubuntu linux: `Linux jenkins14 5.15.102-1-pve #1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64 x86_64 x86_64 GNU/Linux`
```

### Relevant log output

```shell
# code.vegaprotocol.io/vega/cmd/vega

[2023-09-05T14:04:58.467Z] panic: symbol "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" is not an interface

[2023-09-05T14:04:58.467Z] 
[2023-09-05T14:04:58.467Z] goroutine 1 [running]:
[2023-09-05T14:04:58.467Z] cmd/link/internal/ld.(*deadcodePass).decodeIfaceMethod(0x7f93a4afa698?, 0xc00017e900?, 0x841400, 0xc0119d2000?, 0x60)
[2023-09-05T14:04:58.467Z] 	/usr/local/go/src/cmd/link/internal/ld/deadcode.go:423 +0x1b4
[2023-09-05T14:04:58.467Z] cmd/link/internal/ld.(*deadcodePass).flood(0xc0000cea08)
[2023-09-05T14:04:58.467Z] 	/usr/local/go/src/cmd/link/internal/ld/deadcode.go:190 +0xb6f
[2023-09-05T14:04:58.467Z] cmd/link/internal/ld.deadcode(0xc000108000)
[2023-09-05T14:04:58.467Z] 	/usr/local/go/src/cmd/link/internal/ld/deadcode.go:371 +0x216
[2023-09-05T14:04:58.467Z] cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0x0, 0x0}, {0x6946ab, ...}, ...})
[2023-09-05T14:04:58.467Z] 	/usr/local/go/src/cmd/link/internal/ld/main.go:271 +0xef2
[2023-09-05T14:04:58.467Z] main.main()
[2023-09-05T14:04:58.467Z] 	/usr/local/go/src/cmd/link/main.go:72 +0xedb
[2023-09-05T14:04:58.467Z] make: *** [Makefile:170: build-vega-core-upgrade-version] Error 1
```

**Comment by daniel1302** [comment]
@gordsport yess, still trying to confirm it

**Comment by daniel1302** [comment]
The issue is in the compiler. But it is impossible to solve by core. To mitigate it we created an issue in devops-infra repo: https://github.com/vegaprotocol/devops-infra/issues/2048

I am going to close this issue.
