### ISSUE TITLE
Tendermint panic: could not find validator set for height #11002

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9400]
Failed in system test nightly run
panic: could not find validator set for height #11002

goroutine 269 [running]:
github.com/tendermint/tendermint/state.getBeginBlockValidatorInfo(0xc00fb485a0, {0x5aa4b20, 0xc001611458}, 0x1)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:346 +0x3ea
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x5a7f1d0?, 0xc0003a6ff0}, {0x5a931e0, 0xc0016749d0}, 0xc00fb485a0, {0x5aa4b20, 0xc001611458}, 0x2afa?)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:293 +0x234
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0x51da778, 0x7}}, {0xc00171fff0, 0xb}, 0x1, 0x2afa, {{0xc00f9a08e0, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0014181c0, 0x1)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/blockchain/v0/reactor.go:400 +0xbda
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/blockchain/v0/reactor.go:127 +0xe5

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/8715/artifact/testnet/logs/testnet-nodeset-full-3-full/

**Comment by jgsbennett** [comment]
Seen what looks like the same issue in [last night's run](https://jenkins.vega.rocks/job/common/job/system-tests-nightly/34/testReport/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_ethereum_oracles/):
```
        assert data_source["oracleSpec"]["dataSourceSpec"]["spec"]["id"] == data_spec_id
>       assert data_source["oracleSpec"]["dataSourceSpec"]["spec"]["status"] == status
E       AssertionError: assert 'STATUS_ACTIVE' == 'STATUS_DEACTIVATED'
E         - STATUS_DEACTIVATED
E         ?        --     -- -
E         + STATUS_ACTIVE

modules/oraclesMod/oracleMod.py:721: AssertionError
-------------------- ERROR FOUND WITH NETWORK. ERROR 1 of 2 --------------------
Trace from file: /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/logs/testnet-nodeset-full-3-full/vega-full-3.stderr-2023-09-21T02:26:04Z.log

panic: could not find validator set for height #7533

goroutine 187 [running]:
github.com/tendermint/tendermint/state.getBeginBlockValidatorInfo(0xc00e4170e0, {0x5ad6420, 0xc0014994b8}, 0x1)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:346 +0x3ea
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x5ab0970?, 0xc000026c38}, {0x5ac4a00, 0xc000fc84d0}, 0xc00e4170e0, {0x5ad6420, 0xc0014994b8}, 0x1d6d?)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:293 +0x234
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc00ce2cc30, 0x7}}, {0xc00ce2cc40, 0xb}, 0x1, 0x1d6d, {{0xc01837c700, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00ce521c0, 0x0)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/blockchain/v0/reactor.go:400 +0xbda
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/blockchain/v0/reactor.go:112 +0x7a

-------------------- ERROR FOUND WITH NETWORK. ERROR 2 of 2 --------------------
Trace from file: /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/logs/testnet-nodeset-full-3-full/vega-full-3.stderr-2023-09-21T03:13:56Z.log

panic: could not find validator set for height #11970

goroutine 190 [running]:
github.com/tendermint/tendermint/state.getBeginBlockValidatorInfo(0xc012d04000, {0x5ad6420, 0xc000241fc8}, 0x1)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:346 +0x3ea
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x5ab0970?, 0xc000014be0}, {0x5ac4a00, 0xc0015a5090}, 0xc012d04000, {0x5ad6420, 0xc000241fc8}, 0x2ec2?)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:293 +0x234
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0xc00ccf7630, 0x7}}, {0xc00ccf7640, 0xb}, 0x1, 0x2ec2, {{0xc015a386c0, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc001702a80, 0x0)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/blockchain/v0/reactor.go:400 +0xbda
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/blockchain/v0/reactor.go:112 +0x7a
```

**Comment by gordsport** [comment]
@wwestgarth @ze97286 - please can you take a quick look at this and advise if this should be closed or investigated further
