### ISSUE TITLE
[Bug]: Panic on overnight system-test run

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#9443]
### Problem encountered

```
-------------------- ERROR FOUND WITH NETWORK. ERROR 1 of 1 --------------------
Trace from file: /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/logs/testnet-nodeset-validators-1-validator/vega-validator-1.stderr-2023-09-16T01:03:00Z.log

panic: Could not save the snapshot tree [recovered]
	panic: Panic occurred

goroutine 1284929 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc005108300?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc001ef6d00, {0xc004e86ec0, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0x51f3129?, {0x5263a1c?, 0x499d5a0?}, {0xc004e86ec0, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
code.vegaprotocol.io/vega/core/snapshot.(*Engine).snapshotNow.func4.1()
	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:696 +0x155
panic({0x499d5a0, 0xc001244e20})
	/usr/local/go/src/runtime/panic.go:884 +0x213
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x1?, 0x1?, {0x0?, 0x0?, 0xc007d00a40?})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc006a67930, {0xc004e86e40, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
go.uber.org/zap.(*Logger).Panic(0xc00141cec0?, {0x5397f83?, 0xc00756c6c0?}, {0xc004e86e40, 0x1, 0x1})
	/jenkins/GOPATH/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
code.vegaprotocol.io/vega/core/snapshot.(*Engine).snapshotNow.func4()
	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:704 +0x1ae
code.vegaprotocol.io/vega/core/snapshot.(*Engine).snapshotNow.func5()
	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:720 +0x26
created by code.vegaprotocol.io/vega/core/snapshot.(*Engine).snapshotNow
	/jenkins/workspace/common/system-tests-wrapper/vega/core/snapshot/engine.go:719 +0x11fd
```

### Observed behaviour

panic

### Expected behaviour

no panic

### Steps to reproduce

```bash
1. nightly run of system-test
```

### Software version

dev branch

### Failing test

test_margins_recalculated_if_risk_factors_updated[rmod_tau-datanode_risk_path2-0.00022815423226100844]

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-nightly/27/testReport/tests.margins/margins_test/Call_tests___full_g_n___test_margins_recalculated_if_risk_factors_updated_rmod_tau_datanode_risk_path2_0_00022815423226100844_/

**Comment by Sohill-Patel** [comment]
closing issue, related to  out-of-memory issues `002634.ldb: no space left on device`
