### ISSUE TITLE
[Bug]: panic: runtime error: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by fkondej** [vegaprotocol/vega#9488]
### Problem encountered

Restarting the validator on Stagnet from a remote snapshot, we got a panic.
Note:
- we had done Protocol Upgrade from `v0.72.14` (the Mainnet version) to `v0.73.0-preview.4` before the following problem,
- the node ran into `panic: block.AppHash does not match` issues, probably closed by the below - that is why we decided to restart it from remote snapshot,
- not sure if this is relevant, but we had temporal issues with the Sepolia Ethereum nodes

### Observed behaviour

Validator stopped.

### Expected behaviour

Validator should start up.

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

v0.73.0-preview.4

### Failing test

-

### Jenkins run

-

### Configuration used

```shell
Stagnet
```

### Relevant log output

```shell
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: 2023-09-19T19:32:21.551Z        INFO        core.protocol.snapshot        snapshot/engine.go:320        snapshot engine successfully initialised
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc48402]
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: goroutine 569 [running]:
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: code.vegaprotocol.io/vega/core/types.KeyFromPayload({0x0, 0x0})
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/work/vega/vega/core/types/snapshot_nodes.go:4272 +0x22
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: code.vegaprotocol.io/vega/core/types.(*Payload).GetTreeKey(...)
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/work/vega/vega/core/types/snapshot_nodes.go:865
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: code.vegaprotocol.io/vega/core/types.(*Snapshot).TreeFromSnapshot(0xc00c5d5560, 0x0?)
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/work/vega/vega/core/types/snapshot.go:200 +0x1ea
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: code.vegaprotocol.io/vega/core/snapshot.(*Engine).ApplySnapshot(0xc000f67c00, {0x373f85d?, 0x355d6ad?})
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/work/vega/vega/core/snapshot/engine.go:538 +0x57
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: code.vegaprotocol.io/vega/core/processor.(*App).ApplySnapshotChunk(0xc00149a900, {0x3e2b578, 0xc000074060}, {0x0, {0xc00f6f4000, 0xbb891f, 0xbb8920}, {0xc009847980, 0x28}})
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/work/vega/vega/core/processor/abci.go:670 +0x788
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: code.vegaprotocol.io/vega/core/blockchain/abci.(*App).ApplySnapshotChunk(0x7f308ae574c8?, {0x0, {0xc00f6f4000, 0xbb891f, 0xbb8920}, {0xc009847980, 0x28}})
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/work/vega/vega/core/blockchain/abci/abci.go:182 +0xc3
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: code.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).ApplySnapshotChunk(0x41170b?, {0x0, {0xc00f6f4000, 0xbb891f, 0xbb8920}, {0xc009847980, 0x28}})
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/work/vega/vega/cmd/vega/commands/node/app_wrapper.go:92 +0xa9
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: github.com/tendermint/tendermint/abci/client.(*localClient).ApplySnapshotChunkSync(0xc0013737a0, {0x0, {0xc00f6f4000, 0xbb891f, 0xbb8920}, {0xc009847980, 0x28}})
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/abci/client/local_client.go:322 +0x142
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: github.com/tendermint/tendermint/proxy.(*appConnSnapshot).ApplySnapshotChunkSync(0xc00c5419f0?, {0x0, {0xc00f6f4000, 0xbb891f, 0xbb8920}, {0xc009847980, 0x28}})
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/proxy/app_conn.go:194 +0x47
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: github.com/tendermint/tendermint/statesync.(*syncer).applyChunks(0xc00978d7a0, 0x3e2b5b0?)
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/statesync/syncer.go:367 +0x13a
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: github.com/tendermint/tendermint/statesync.(*syncer).Sync(_, _, _)
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/statesync/syncer.go:303 +0xc0a
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: github.com/tendermint/tendermint/statesync.(*syncer).SyncAny(_, _, _)
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/statesync/syncer.go:185 +0x4be
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: github.com/tendermint/tendermint/statesync.(*Reactor).Sync(_, {_, _}, _)
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/statesync/reactor.go:303 +0x4d7
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: github.com/tendermint/tendermint/node.startStateSync.func1()
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/node/node.go:675 +0xc5
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]: created by github.com/tendermint/tendermint/node.startStateSync
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687955]:         /home/runner/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/node/node.go:674 +0x48c
Sep 19 19:32:21 n01.stagnet1.vega.rocks visor[687730]: 2023-09-19T19:32:21.596Z        ERROR        visor        visor/visor.go:143        Binaries executions has failed        {"error": "failed after waiting for binary /home/vega/vegavisor_home/current/vega [start --home /home/vega/vega_home --tendermint-home /home/vega/tendermint_home --nodewallet-passphrase-file /home/vega/vega_home/all-wallet-passphrase.txt --snapshot.load-from-block-height 6688664]: exit status 2"}
```

**Comment by ze97286** [comment]
@fkondej the log lines above seem to imply that the node was running with v0.72.14 rather than with the post-protocol upgrade intended version v0.73.0-preview.4. Can you please double check the binary upgrade took place?

**Comment by fkondej** [comment]
you are right it was running wrong version @wwestgarth noticed this.
