### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26db554]

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9628]
[https://jenkins.vega.rocks/job/common/job/system-tests-nightly/46/testReport/junit/tes[…]ll_tests___full_a_f___test_datanode_restore_from_dehistory/](https://jenkins.vega.rocks/job/common/job/system-tests-nightly/46/testReport/junit/tests.datanode/datanode_test/Call_tests___full_a_f___test_datanode_restore_from_dehistory/)

```
Trace from file: /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/logs/testnet-nodeset-full-7-full/vega-full-7.stderr-2023-09-30T02:38:28Z.log

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x26db554]

goroutine 144 [running]:
github.com/tendermint/tendermint/light/provider/http.(*http).LightBlock(0xc0000d3b40, {0x5b7a798, 0xc000e11db0}, 0x0)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/light/provider/http/http.go:86 +0x134
github.com/tendermint/tendermint/light.(*Client).getTargetBlockOrLatest(0xc0000d3b40?, {0x5b7a798, 0xc000e11db0}, 0x249c, {0x5b72c60, 0xc0000d3b40})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/light/detector.go:384 +0x3c
github.com/tendermint/tendermint/light.(*Client).compareNewHeaderWithWitness(0xc000e7a900, {0x5b7a798, 0xc000e11db0}, 0x0?, 0xc0012cf398, {0x5b72c60, 0xc0000d3b40}, 0x5)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/light/detector.go:138 +0x27a
created by github.com/tendermint/tendermint/light.(*Client).compareFirstHeaderWithWitnesses
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/light/client.go:1144 +0x1bd

```

**Comment by vega-paul** [comment]
William Westgarth
  [26 minutes ago](https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1696233438658769?thread_ts=1696101005.113449&cid=C9E6XA8GK)
fwiw the panic is in tendermint and has been fixed recently in cometBFT:
[light] Fixed an edge case where a light client would panic when attempting to query a node that (1) has started from a non-zero height and (2) does not yet have any data. The light client will now, correctly, not panic and keep the node in its list of providers in the same way it would if it queried a node starting from height zero that does not yet have data (#1340
